'use strict';

function LetterSet() {

	this.lowerSet = {
		'á': {shift: 'Á', html: '&#_ZZ_;', hex: null, name: 'aacute', info: 'small a, acute accent'},
		'â': {shift: 'Â', html: '&#_ZZ_;', hex: null, name: 'acirc', info: 'small a, circumflex accent'},
		'à': {shift: 'À', html: '&#_ZZ_;', hex: null, name: 'agrave', info: 'small a, grave accent'},
		'å': {shift: 'Å', html: '&#_ZZ_;', hex: null, name: 'aring', info: 'small a, ring'},
		'ã': {shift: 'Ã', html: '&#_ZZ_;', hex: null, name: 'atilde', info: 'small a, tilde'},
		'ä': {shift: 'Ä', html: '&#_ZZ_;', hex: null, name: 'auml', info: 'small a, dieresis or umlautmark'},
		'æ': {shift: 'Æ', html: '&#_ZZ_;', hex: null, name: 'aelig', info: 'small ae diphthong (ligature)'},
		'ç': {shift: 'Ç', html: '&#_ZZ_;', hex: null, name: 'ccedil', info: 'small c, cedilla'},
		'ð': {shift: 'Ð', html: '&#_ZZ_;', hex: null, name: 'eth', info: 'small eth, Icelandic'},
		'é': {shift: 'É', html: '&#_ZZ_;', hex: null, name: 'eacute', info: 'small e, acute accent'},
		'ê': {shift: 'Ê', html: '&#_ZZ_;', hex: null, name: 'ecirc', info: 'small e, circumflex accent'},
		'è': {shift: 'È', html: '&#_ZZ_;', hex: null, name: 'egrave', info: 'small e, grave accent'},
		'ë': {shift: 'Ë', html: '&#_ZZ_;', hex: null, name: 'euml', info: 'small e, dieresis or umlautmark'},
		'í': {shift: 'Í', html: '&#_ZZ_;', hex: null, name: 'iacute', info: 'small i, acute accent'},
		'î': {shift: 'Î', html: '&#_ZZ_;', hex: null, name: 'icirc', info: 'small i, circumflex accent'},
		'ì': {shift: 'Ì', html: '&#_ZZ_;', hex: null, name: 'igrave', info: 'small i, grave accent'},
		'ï': {shift: 'Ï', html: '&#_ZZ_;', hex: null, name: 'iuml', info: 'small i, dieresis or umlautmark'},
		'ñ': {shift: 'Ñ', html: '&#_ZZ_;', hex: null, name: 'ntilde', info: 'small n, tilde'},
		'ó': {shift: 'Ó', html: '&#_ZZ_;', hex: null, name: 'oacute', info: 'small o, acute accent'},
		'ô': {shift: 'Ô', html: '&#_ZZ_;', hex: null, name: 'ocirc', info: 'small o, circumflex accent'},
		'ò': {shift: 'Ò', html: '&#_ZZ_;', hex: null, name: 'ograve', info: 'small o, grave accent'},
		'ø': {shift: 'Ø', html: '&#_ZZ_;', hex: null, name: 'oslash', info: 'small o, slash'},
		'õ': {shift: 'Õ', html: '&#_ZZ_;', hex: null, name: 'otilde', info: 'small o, tilde'},
		'ö': {shift: 'Ö', html: '&#_ZZ_;', hex: null, name: 'ouml', info: 'small o, dieresis or umlautmark'},
		'ß': {shift: 'SS', html: '&#_ZZ_;', hex: null, name: 'szlig', info: 'small sharp s, German (szligature)'},
		'þ': {shift: 'Þ', html: '&#_ZZ_;', hex: null, name: 'thorn', info: 'small thorn, Icelandic'},
		'Þ': {shift: 'þ', html: '&#_ZZ_;', hex: null, name: 'THORN', info: 'capital THORN, Icelandic'},
		'ú': {shift: 'Ú', html: '&#_ZZ_;', hex: null, name: 'uacute', info: 'small u, acute accent'},
		'û': {shift: 'Û', html: '&#_ZZ_;', hex: null, name: 'ucirc', info: 'small u, circumflex accent'},
		'ù': {shift: 'Ù', html: '&#_ZZ_;', hex: null, name: 'ugrave', info: 'small u, grave accent'},
		'ü': {shift: 'Ü', html: '&#_ZZ_;', hex: null, name: 'uuml', info: 'small u, dieresis or umlautmark'},
		'ý': {shift: 'Ý', html: '&#_ZZ_;', hex: null, name: 'yacute', info: 'small y, acute accent'},
		'ÿ': {shift: '', html: '&#_ZZ_;', hex: null, name: 'yuml', info: 'small y, dieresis or umlautmark'},
		'a': {shift: 'A', html: '&#97;', hex: 0x61 },
		'b': {shift: 'B', html: '&#98;', hex: 0x62 },
		'c': {shift: 'C', html: '&#99;', hex: 0x63 },
		'd': {shift: 'D', html: '&#100;', hex: 0x64 },
		'e': {shift: 'E', html: '&#101;', hex: 0x65 },
		'f': {shift: 'F', html: '&#102;', hex: 0x66 },
		'g': {shift: 'G', html: '&#103;', hex: 0x67 },
		'h': {shift: 'H', html: '&#104;', hex: 0x68 },
		'i': {shift: 'I', html: '&#105;', hex: 0x69 },
		'j': {shift: 'J', html: '&#106;', hex: 0x6A },
		'k': {shift: 'K', html: '&#107;', hex: 0x6B },
		'l': {shift: 'L', html: '&#108;', hex: 0x6C },
		'm': {shift: 'M', html: '&#109;', hex: 0x6D },
		'n': {shift: 'N', html: '&#110;', hex: 0x6E },
		'o': {shift: 'O', html: '&#111;', hex: 0x6F },
		'p': {shift: 'P', html: '&#112;', hex: 0x70 },
		'q': {shift: 'Q', html: '&#113;', hex: 0x71 },
		'r': {shift: 'R', html: '&#114;', hex: 0x72 },
		's': {shift: 'S', html: '&#115;', hex: 0x73 },
		't': {shift: 'T', html: '&#116;', hex: 0x74 },
		'u': {shift: 'U', html: '&#117;', hex: 0x75 },
		'v': {shift: 'V', html: '&#118;', hex: 0x76 },
		'w': {shift: 'W', html: '&#119;', hex: 0x77 },
		'x': {shift: 'X', html: '&#120;', hex: 0x78 },
		'y': {shift: 'Y', html: '&#121;', hex: 0x79 },
		'z': {shift: 'Z', html: '&#122;', hex: 0x7A }
	};

	this.upperSet = {
		'Á': {shift: 'á', html: '&#_ZZ_;', hex: null, name: 'Aacute', info: 'capital A, acute accent'},
		'Â': {shift: 'â', html: '&#_ZZ_;', hex: null, name: 'Acirc', info: 'capital A, circumflex accent'},
		'À': {shift: 'à', html: '&#_ZZ_;', hex: null, name: 'Agrave', info: 'capital A, grave accent'},
		'Å': {shift: 'å', html: '&#_ZZ_;', hex: null, name: 'Aring', info: 'capital A, ring'},
		'Ã': {shift: 'ã', html: '&#_ZZ_;', hex: null, name: 'Atilde', info: 'capital A, tilde'},
		'Ä': {shift: 'ä', html: '&#_ZZ_;', hex: null, name: 'Auml', info: 'capital A, dieresis or umlautmark'},
		'Æ': {shift: 'æ', html: '&#_ZZ_;', hex: null, name: 'AElig', info: 'capital AE diphthong(ligature)'},
		'Ç': {shift: 'ç', html: '&#_ZZ_;', hex: null, name: 'Ccedil', info: 'capital C, cedilla'},
		'Ð': {shift: 'ð', html: '&#_ZZ_;', hex: null, name: 'ETH', info: 'capital Eth, Icelandic'},
		'É': {shift: 'é', html: '&#_ZZ_;', hex: null, name: 'Eacute', info: 'capital E, acute accent'},
		'Ê': {shift: 'ê', html: '&#_ZZ_;', hex: null, name: 'Ecirc', info: 'capital E, circumflex accent'},
		'È': {shift: 'è', html: '&#_ZZ_;', hex: null, name: 'Egrave', info: 'capital E, grave accent'},
		'Ë': {shift: 'ë', html: '&#_ZZ_;', hex: null, name: 'Euml', info: 'capital E, dieresis or umlautmark'},
		'Í': {shift: 'í', html: '&#_ZZ_;', hex: null, name: 'Iacute', info: 'capital I, acute accent'},
		'Î': {shift: 'î', html: '&#_ZZ_;', hex: null, name: 'Icirc', info: 'capital I, circumflex accent'},
		'Ì': {shift: 'ì', html: '&#_ZZ_;', hex: null, name: 'Igrave', info: 'capital I, grave accent'},
		'Ï': {shift: 'ï', html: '&#_ZZ_;', hex: null, name: 'Iuml', info: 'capital I, dieresis or umlautmark'},
		'Ñ': {shift: 'ñ', html: '&#_ZZ_;', hex: null, name: 'Ntilde', info: 'capital N, tilde'},
		'Ó': {shift: 'ó', html: '&#_ZZ_;', hex: null, name: 'Oacute', info: 'capital O, acute accent'},
		'Ô': {shift: 'ô', html: '&#_ZZ_;', hex: null, name: 'Ocirc', info: 'capital O, circumflex accent'},
		'Ò': {shift: 'ò', html: '&#_ZZ_;', hex: null, name: 'Ograve', info: 'capital O, grave accent'},
		'Ø': {shift: 'ø', html: '&#_ZZ_;', hex: null, name: 'Oslash', info: 'capital O, slash'},
		'Õ': {shift: 'õ', html: '&#_ZZ_;', hex: null, name: 'Otilde', info: 'capital O, tilde'},
		'Ö': {shift: 'ö', html: '&#_ZZ_;', hex: null, name: 'Ouml', info: 'capital O, dieresis or umlautmark'},
		'Ú': {shift: 'ú', html: '&#_ZZ_;', hex: null, name: 'Uacute', info: 'capital U, acute accent'},
		'Û': {shift: 'û', html: '&#_ZZ_;', hex: null, name: 'Ucirc', info: 'capital U, circumflex accent'},
		'Ù': {shift: 'ù', html: '&#_ZZ_;', hex: null, name: 'Ugrave', info: 'capital U, grave accent'},
		'Ü': {shift: 'ü', html: '&#_ZZ_;', hex: null, name: 'Uuml', info: 'capital U, dieresis or umlautmark'},
		'Ý': {shift: 'ý', html: '&#_ZZ_;', hex: null, name: 'Yacute', info: 'capital Y, acute accent'},
		'A': {shift: 'a', html: '&#65;', hex: 0x41, name: 'Yacute'},
		'B': {shift: 'b', html: '&#66;', hex: 0x42, name: 'Yacute'},
		'C': {shift: 'c', html: '&#67;', hex: 0x43, name: 'Yacute'},
		'D': {shift: 'd', html: '&#68;', hex: 0x44, name: 'Yacute'},
		'E': {shift: 'e', html: '&#69;', hex: 0x45, name: 'Yacute'},
		'F': {shift: 'f', html: '&#70;', hex: 0x46, name: 'Yacute'},
		'G': {shift: 'g', html: '&#71;', hex: 0x47, name: 'Yacute'},
		'H': {shift: 'h', html: '&#72;', hex: 0x48, name: 'Yacute'},
		'I': {shift: 'i', html: '&#73;', hex: 0x49, name: 'Yacute'},
		'J': {shift: 'j', html: '&#74;', hex: 0x4A, name: 'Yacute'},
		'K': {shift: 'k', html: '&#75;', hex: 0x4B, name: 'Yacute'},
		'L': {shift: 'l', html: '&#76;', hex: 0x4C, name: 'Yacute'},
		'M': {shift: 'm', html: '&#77;', hex: 0x4D, name: 'Yacute'},
		'N': {shift: 'n', html: '&#78;', hex: 0x4E, name: 'Yacute'},
		'O': {shift: 'o', html: '&#79;', hex: 0x4F, name: 'Yacute'},
		'P': {shift: 'p', html: '&#80;', hex: 0x50, name: 'Yacute'},
		'Q': {shift: 'q', html: '&#81;', hex: 0x51, name: 'Yacute'},
		'R': {shift: 'r', html: '&#82;', hex: 0x52, name: 'Yacute'},
		'S': {shift: 's', html: '&#83;', hex: 0x53, name: 'Yacute'},
		'T': {shift: 't', html: '&#84;', hex: 0x54, name: 'Yacute'},
		'U': {shift: 'u', html: '&#85;', hex: 0x55, name: 'Yacute'},
		'V': {shift: 'v', html: '&#86;', hex: 0x56, name: 'Yacute'},
		'W': {shift: 'w', html: '&#87;', hex: 0x57, name: 'Yacute'},
		'X': {shift: 'x', html: '&#88;', hex: 0x58, name: 'Yacute'},
		'Y': {shift: 't', html: '&#89;', hex: 0x59, name: 'Yacute'},
		'Z': {shift: 'z', html: '&#90;', hex: 0x5A, name: 'Yacute'}
}

		this.braileSet = {
			'⠁': {shift: 'ZZZ', decimal: '&#10241;', hex: '', title: ''},
			'⠂': {shift: 'ZZZ', decimal: '&#10242;', hex: '', title: ''},
			'⠃': {shift: 'ZZZ', decimal: '&#10243;', hex: '', title: ''},
			'⠄': {shift: 'ZZZ', decimal: '&#10244;', hex: '', title: ''},
			'⠅': {shift: 'ZZZ', decimal: '&#10245;', hex: '', title: ''},
			'⠆': {shift: 'ZZZ', decimal: '&#10246;', hex: '', title: ''},
			'⠇': {shift: 'ZZZ', decimal: '&#10247;', hex: '', title: ''},
			'⠈': {shift: 'ZZZ', decimal: '&#10248;', hex: '', title: ''},
			'⠉': {shift: 'ZZZ', decimal: '&#10249;', hex: '', title: ''},
			'⠊': {shift: 'ZZZ', decimal: '&#10250;', hex: '', title: ''},
			'⠋': {shift: 'ZZZ', decimal: '&#10251;', hex: '', title: ''},
			'⠌': {shift: 'ZZZ', decimal: '&#10252;', hex: '', title: ''},
			'⠍': {shift: 'ZZZ', decimal: '&#10253;', hex: '', title: ''},
			'⠎': {shift: 'ZZZ', decimal: '&#10254;', hex: '', title: ''},
			'⠏': {shift: 'ZZZ', decimal: '&#10255;', hex: '', title: ''},
			'⠐': {shift: 'ZZZ', decimal: '&#10256;', hex: '', title: ''},
			'⠑': {shift: 'ZZZ', decimal: '&#10257;', hex: '', title: ''},
			'⠒': {shift: 'ZZZ', decimal: '&#10258;', hex: '', title: ''},
			'⠓': {shift: 'ZZZ', decimal: '&#10259;', hex: '', title: ''},
			'⠔': {shift: 'ZZZ', decimal: '&#10260;', hex: '', title: ''},
			'⠕': {shift: 'ZZZ', decimal: '&#10261;', hex: '', title: ''},
			'⠖': {shift: 'ZZZ', decimal: '&#10262;', hex: '', title: ''},
			'⠗': {shift: 'ZZZ', decimal: '&#10263;', hex: '', title: ''},
			'⠘': {shift: 'ZZZ', decimal: '&#10264;', hex: '', title: ''},
			'⠙': {shift: 'ZZZ', decimal: '&#10265;', hex: '', title: ''},
			'⠚': {shift: 'ZZZ', decimal: '&#10266;', hex: '', title: ''},
			'⠛': {shift: 'ZZZ', decimal: '&#10267;', hex: '', title: ''},
			'⠜': {shift: 'ZZZ', decimal: '&#10268;', hex: '', title: ''},
			'⠝': {shift: 'ZZZ', decimal: '&#10269;', hex: '', title: ''},
			'⠞': {shift: 'ZZZ', decimal: '&#10270;', hex: '', title: ''},
			'⠟': {shift: 'ZZZ', decimal: '&#10271;', hex: '', title: ''},
			'⠠': {shift: 'ZZZ', decimal: '&#10272;', hex: '', title: ''},
			'⠡': {shift: 'ZZZ', decimal: '&#10273;', hex: '', title: ''},
			'⠢': {shift: 'ZZZ', decimal: '&#10274;', hex: '', title: ''},
			'⠣': {shift: 'ZZZ', decimal: '&#10275;', hex: '', title: ''},
			'⠤': {shift: 'ZZZ', decimal: '&#10276;', hex: '', title: ''},
			'⠥': {shift: 'ZZZ', decimal: '&#10277;', hex: '', title: ''},
			'⠦': {shift: 'ZZZ', decimal: '&#10278;', hex: '', title: ''},
			'⠧': {shift: 'ZZZ', decimal: '&#10279;', hex: '', title: ''},
			'⠨': {shift: 'ZZZ', decimal: '&#10280;', hex: '', title: ''},
			'⠩': {shift: 'ZZZ', decimal: '&#10281;', hex: '', title: ''},
			'⠪': {shift: 'ZZZ', decimal: '&#10282;', hex: '', title: ''},
			'⠫': {shift: 'ZZZ', decimal: '&#10283;', hex: '', title: ''},
			'⠬': {shift: 'ZZZ', decimal: '&#10284;', hex: '', title: ''},
			'⠭': {shift: 'ZZZ', decimal: '&#10285;', hex: '', title: ''},
			'⠮': {shift: 'ZZZ', decimal: '&#10286;', hex: '', title: ''},
			'⠯': {shift: 'ZZZ', decimal: '&#10287;', hex: '', title: ''},
			'⠰': {shift: 'ZZZ', decimal: '&#10288;', hex: '', title: ''},
			'⠱': {shift: 'ZZZ', decimal: '&#10289;', hex: '', title: ''},
			'⠲': {shift: 'ZZZ', decimal: '&#10290;', hex: '', title: ''},
			'⠳': {shift: 'ZZZ', decimal: '&#10291;', hex: '', title: ''},
			'⠴': {shift: 'ZZZ', decimal: '&#10292;', hex: '', title: ''},
			'⠵': {shift: 'ZZZ', decimal: '&#10293;', hex: '', title: ''},
			'⠶': {shift: 'ZZZ', decimal: '&#10294;', hex: '', title: ''},
			'⠷': {shift: 'ZZZ', decimal: '&#10295;', hex: '', title: ''},
			'⠸': {shift: 'ZZZ', decimal: '&#10296;', hex: '', title: ''},
			'⠹': {shift: 'ZZZ', decimal: '&#10297;', hex: '', title: ''},
			'⠺': {shift: 'ZZZ', decimal: '&#10298;', hex: '', title: ''},
			'⠻': {shift: 'ZZZ', decimal: '&#10299;', hex: '', title: ''},
			'⠼': {shift: 'ZZZ', decimal: '&#10300;', hex: '', title: ''},
			'⠽': {shift: 'ZZZ', decimal: '&#10301;', hex: '', title: ''},
			'⠾': {shift: 'ZZZ', decimal: '&#10302;', hex: '', title: ''},
			'⠿': {shift: 'ZZZ', decimal: '&#10303;', hex: '', title: ''},
			'⡀': {shift: 'ZZZ', decimal: '&#10304;', hex: '', title: ''},
			'⡁': {shift: 'ZZZ', decimal: '&#10305;', hex: '', title: ''},
			'⡂': {shift: 'ZZZ', decimal: '&#10306;', hex: '', title: ''},
			'⡃': {shift: 'ZZZ', decimal: '&#10307;', hex: '', title: ''},
			'⡄': {shift: 'ZZZ', decimal: '&#10308;', hex: '', title: ''},
			'⡅': {shift: 'ZZZ', decimal: '&#10309;', hex: '', title: ''},
			'⡆': {shift: 'ZZZ', decimal: '&#10310;', hex: '', title: ''},
			'⡇': {shift: 'ZZZ', decimal: '&#10311;', hex: '', title: ''},
			'⡈': {shift: 'ZZZ', decimal: '&#10312;', hex: '', title: ''},
			'⡉': {shift: 'ZZZ', decimal: '&#10313;', hex: '', title: ''},
			'⡊': {shift: 'ZZZ', decimal: '&#10314;', hex: '', title: ''},
			'⡋': {shift: 'ZZZ', decimal: '&#10315;', hex: '', title: ''},
			'⡌': {shift: 'ZZZ', decimal: '&#10316;', hex: '', title: ''},
			'⡍': {shift: 'ZZZ', decimal: '&#10317;', hex: '', title: ''},
			'⡎': {shift: 'ZZZ', decimal: '&#10318;', hex: '', title: ''},
			'⡏': {shift: 'ZZZ', decimal: '&#10319;', hex: '', title: ''},
			'⡐': {shift: 'ZZZ', decimal: '&#10320;', hex: '', title: ''},
			'⡑': {shift: 'ZZZ', decimal: '&#10321;', hex: '', title: ''},
			'⡒': {shift: 'ZZZ', decimal: '&#10322;', hex: '', title: ''},
			'⡓': {shift: 'ZZZ', decimal: '&#10323;', hex: '', title: ''},
			'⡔': {shift: 'ZZZ', decimal: '&#10324;', hex: '', title: ''},
			'⡕': {shift: 'ZZZ', decimal: '&#10325;', hex: '', title: ''},
			'⡖': {shift: 'ZZZ', decimal: '&#10326;', hex: '', title: ''},
			'⡗': {shift: 'ZZZ', decimal: '&#10327;', hex: '', title: ''},
			'⡘': {shift: 'ZZZ', decimal: '&#10328;', hex: '', title: ''},
			'⡙': {shift: 'ZZZ', decimal: '&#10329;', hex: '', title: ''},
			'⡚': {shift: 'ZZZ', decimal: '&#10330;', hex: '', title: ''},
			'⡛': {shift: 'ZZZ', decimal: '&#10331;', hex: '', title: ''},
			'⡜': {shift: 'ZZZ', decimal: '&#10332;', hex: '', title: ''},
			'⡝': {shift: 'ZZZ', decimal: '&#10333;', hex: '', title: ''},
			'⡞': {shift: 'ZZZ', decimal: '&#10334;', hex: '', title: ''},
			'⡟': {shift: 'ZZZ', decimal: '&#10335;', hex: '', title: ''},
			'⡠': {shift: 'ZZZ', decimal: '&#10336;', hex: '', title: ''},
			'⡡': {shift: 'ZZZ', decimal: '&#10337;', hex: '', title: ''},
			'⡢': {shift: 'ZZZ', decimal: '&#10338;', hex: '', title: ''},
			'⡣': {shift: 'ZZZ', decimal: '&#10339;', hex: '', title: ''},
			'⡤': {shift: 'ZZZ', decimal: '&#10340;', hex: '', title: ''},
			'⡥': {shift: 'ZZZ', decimal: '&#10341;', hex: '', title: ''},
			'⡦': {shift: 'ZZZ', decimal: '&#10342;', hex: '', title: ''},
			'⡧': {shift: 'ZZZ', decimal: '&#10343;', hex: '', title: ''},
			'⡨': {shift: 'ZZZ', decimal: '&#10344;', hex: '', title: ''},
			'⡩': {shift: 'ZZZ', decimal: '&#10345;', hex: '', title: ''},
			'⡪': {shift: 'ZZZ', decimal: '&#10346;', hex: '', title: ''},
			'⡫': {shift: 'ZZZ', decimal: '&#10347;', hex: '', title: ''},
			'⡬': {shift: 'ZZZ', decimal: '&#10348;', hex: '', title: ''},
			'⡭': {shift: 'ZZZ', decimal: '&#10349;', hex: '', title: ''},
			'⡮': {shift: 'ZZZ', decimal: '&#10350;', hex: '', title: ''},
			'⡯': {shift: 'ZZZ', decimal: '&#10351;', hex: '', title: ''},
			'⡰': {shift: 'ZZZ', decimal: '&#10352;', hex: '', title: ''},
			'⡱': {shift: 'ZZZ', decimal: '&#10353;', hex: '', title: ''},
			'⡲': {shift: 'ZZZ', decimal: '&#10354;', hex: '', title: ''},
			'⡳': {shift: 'ZZZ', decimal: '&#10355;', hex: '', title: ''},
			'⡴': {shift: 'ZZZ', decimal: '&#10356;', hex: '', title: ''},
			'⡵': {shift: 'ZZZ', decimal: '&#10357;', hex: '', title: ''},
			'⡶': {shift: 'ZZZ', decimal: '&#10358;', hex: '', title: ''},
			'⡷': {shift: 'ZZZ', decimal: '&#10359;', hex: '', title: ''},
			'⡸': {shift: 'ZZZ', decimal: '&#10360;', hex: '', title: ''},
			'⡹': {shift: 'ZZZ', decimal: '&#10361;', hex: '', title: ''},
			'⡺': {shift: 'ZZZ', decimal: '&#10362;', hex: '', title: ''},
			'⡻': {shift: 'ZZZ', decimal: '&#10363;', hex: '', title: ''},
			'⡼': {shift: 'ZZZ', decimal: '&#10364;', hex: '', title: ''},
			'⡽': {shift: 'ZZZ', decimal: '&#10365;', hex: '', title: ''},
			'⡾': {shift: 'ZZZ', decimal: '&#10366;', hex: '', title: ''},
			'⡿': {shift: 'ZZZ', decimal: '&#10367;', hex: '', title: ''},
			'⢀': {shift: 'ZZZ', decimal: '&#10368;', hex: '', title: ''},
			'⢁': {shift: 'ZZZ', decimal: '&#10369;', hex: '', title: ''},
			'⢂': {shift: 'ZZZ', decimal: '&#10370;', hex: '', title: ''},
			'⢃': {shift: 'ZZZ', decimal: '&#10371;', hex: '', title: ''},
			'⢄': {shift: 'ZZZ', decimal: '&#10372;', hex: '', title: ''},
			'⢅': {shift: 'ZZZ', decimal: '&#10373;', hex: '', title: ''},
			'⢆': {shift: 'ZZZ', decimal: '&#10374;', hex: '', title: ''},
			'⢇': {shift: 'ZZZ', decimal: '&#10375;', hex: '', title: ''},
			'⢈': {shift: 'ZZZ', decimal: '&#10376;', hex: '', title: ''},
			'⢉': {shift: 'ZZZ', decimal: '&#10377;', hex: '', title: ''},
			'⢊': {shift: 'ZZZ', decimal: '&#10378;', hex: '', title: ''},
			'⢋': {shift: 'ZZZ', decimal: '&#10379;', hex: '', title: ''},
			'⢌': {shift: 'ZZZ', decimal: '&#10380;', hex: '', title: ''},
			'⢍': {shift: 'ZZZ', decimal: '&#10381;', hex: '', title: ''},
			'⢎': {shift: 'ZZZ', decimal: '&#10382;', hex: '', title: ''},
			'⢏': {shift: 'ZZZ', decimal: '&#10383;', hex: '', title: ''},
			'⢐': {shift: 'ZZZ', decimal: '&#10384;', hex: '', title: ''},
			'⢑': {shift: 'ZZZ', decimal: '&#10385;', hex: '', title: ''},
			'⢒': {shift: 'ZZZ', decimal: '&#10386;', hex: '', title: ''},
			'⢓': {shift: 'ZZZ', decimal: '&#10387;', hex: '', title: ''},
			'⢔': {shift: 'ZZZ', decimal: '&#10388;', hex: '', title: ''},
			'⢕': {shift: 'ZZZ', decimal: '&#10389;', hex: '', title: ''},
			'⢖': {shift: 'ZZZ', decimal: '&#10390;', hex: '', title: ''},
			'⢗': {shift: 'ZZZ', decimal: '&#10391;', hex: '', title: ''},
			'⢘': {shift: 'ZZZ', decimal: '&#10392;', hex: '', title: ''},
			'⢙': {shift: 'ZZZ', decimal: '&#10393;', hex: '', title: ''},
			'⢚': {shift: 'ZZZ', decimal: '&#10394;', hex: '', title: ''},
			'⢛': {shift: 'ZZZ', decimal: '&#10395;', hex: '', title: ''},
			'⢜': {shift: 'ZZZ', decimal: '&#10396;', hex: '', title: ''},
			'⢝': {shift: 'ZZZ', decimal: '&#10397;', hex: '', title: ''},
			'⢞': {shift: 'ZZZ', decimal: '&#10398;', hex: '', title: ''},
			'⢟': {shift: 'ZZZ', decimal: '&#10399;', hex: '', title: ''},
			'⢠': {shift: 'ZZZ', decimal: '&#10400;', hex: '', title: ''},
			'⢡': {shift: 'ZZZ', decimal: '&#10401;', hex: '', title: ''},
			'⢢': {shift: 'ZZZ', decimal: '&#10402;', hex: '', title: ''},
			'⢣': {shift: 'ZZZ', decimal: '&#10403;', hex: '', title: ''},
			'⢤': {shift: 'ZZZ', decimal: '&#10404;', hex: '', title: ''},
			'⢥': {shift: 'ZZZ', decimal: '&#10405;', hex: '', title: ''},
			'⢦': {shift: 'ZZZ', decimal: '&#10406;', hex: '', title: ''},
			'⢧': {shift: 'ZZZ', decimal: '&#10407;', hex: '', title: ''},
			'⢨': {shift: 'ZZZ', decimal: '&#10408;', hex: '', title: ''},
			'⢩': {shift: 'ZZZ', decimal: '&#10409;', hex: '', title: ''},
			'⢪': {shift: 'ZZZ', decimal: '&#10410;', hex: '', title: ''},
			'⢫': {shift: 'ZZZ', decimal: '&#10411;', hex: '', title: ''},
			'⢬': {shift: 'ZZZ', decimal: '&#10412;', hex: '', title: ''},
			'⢭': {shift: 'ZZZ', decimal: '&#10413;', hex: '', title: ''},
			'⢮': {shift: 'ZZZ', decimal: '&#10414;', hex: '', title: ''},
			'⢯': {shift: 'ZZZ', decimal: '&#10415;', hex: '', title: ''},
			'⢰': {shift: 'ZZZ', decimal: '&#10416;', hex: '', title: ''},
			'⢱': {shift: 'ZZZ', decimal: '&#10417;', hex: '', title: ''},
			'⢲': {shift: 'ZZZ', decimal: '&#10418;', hex: '', title: ''},
			'⢳': {shift: 'ZZZ', decimal: '&#10419;', hex: '', title: ''},
			'⢴': {shift: 'ZZZ', decimal: '&#10420;', hex: '', title: ''},
			'⢵': {shift: 'ZZZ', decimal: '&#10421;', hex: '', title: ''},
			'⢶': {shift: 'ZZZ', decimal: '&#10422;', hex: '', title: ''},
			'⢷': {shift: 'ZZZ', decimal: '&#10423;', hex: '', title: ''},
			'⢸': {shift: 'ZZZ', decimal: '&#10424;', hex: '', title: ''},
			'⢹': {shift: 'ZZZ', decimal: '&#10425;', hex: '', title: ''},
			'⢺': {shift: 'ZZZ', decimal: '&#10426;', hex: '', title: ''},
			'⢻': {shift: 'ZZZ', decimal: '&#10427;', hex: '', title: ''},
			'⢼': {shift: 'ZZZ', decimal: '&#10428;', hex: '', title: ''},
			'⢽': {shift: 'ZZZ', decimal: '&#10429;', hex: '', title: ''},
			'⢾': {shift: 'ZZZ', decimal: '&#10430;', hex: '', title: ''},
			'⢿': {shift: 'ZZZ', decimal: '&#10431;', hex: '', title: ''},
			'⣀': {shift: 'ZZZ', decimal: '&#10432;', hex: '', title: ''},
			'⣁': {shift: 'ZZZ', decimal: '&#10433;', hex: '', title: ''},
			'⣂': {shift: 'ZZZ', decimal: '&#10434;', hex: '', title: ''},
			'⣃': {shift: 'ZZZ', decimal: '&#10435;', hex: '', title: ''},
			'⣄': {shift: 'ZZZ', decimal: '&#10436;', hex: '', title: ''},
			'⣅': {shift: 'ZZZ', decimal: '&#10437;', hex: '', title: ''},
			'⣆': {shift: 'ZZZ', decimal: '&#10438;', hex: '', title: ''},
			'⣇': {shift: 'ZZZ', decimal: '&#10439;', hex: '', title: ''},
			'⣈': {shift: 'ZZZ', decimal: '&#10440;', hex: '', title: ''},
			'⣉': {shift: 'ZZZ', decimal: '&#10441;', hex: '', title: ''},
			'⣊': {shift: 'ZZZ', decimal: '&#10442;', hex: '', title: ''},
			'⣋': {shift: 'ZZZ', decimal: '&#10443;', hex: '', title: ''},
			'⣌': {shift: 'ZZZ', decimal: '&#10444;', hex: '', title: ''},
			'⣍': {shift: 'ZZZ', decimal: '&#10445;', hex: '', title: ''},
			'⣎': {shift: 'ZZZ', decimal: '&#10446;', hex: '', title: ''},
			'⣏': {shift: 'ZZZ', decimal: '&#10447;', hex: '', title: ''},
			'⣐': {shift: 'ZZZ', decimal: '&#10448;', hex: '', title: ''},
			'⣑': {shift: 'ZZZ', decimal: '&#10449;', hex: '', title: ''},
			'⣒': {shift: 'ZZZ', decimal: '&#10450;', hex: '', title: ''},
			'⣓': {shift: 'ZZZ', decimal: '&#10451;', hex: '', title: ''},
			'⣔': {shift: 'ZZZ', decimal: '&#10452;', hex: '', title: ''},
			'⣕': {shift: 'ZZZ', decimal: '&#10453;', hex: '', title: ''},
			'⣖': {shift: 'ZZZ', decimal: '&#10454;', hex: '', title: ''},
			'⣗': {shift: 'ZZZ', decimal: '&#10455;', hex: '', title: ''},
			'⣘': {shift: 'ZZZ', decimal: '&#10456;', hex: '', title: ''},
			'⣙': {shift: 'ZZZ', decimal: '&#10457;', hex: '', title: ''},
			'⣚': {shift: 'ZZZ', decimal: '&#10458;', hex: '', title: ''},
			'⣛': {shift: 'ZZZ', decimal: '&#10459;', hex: '', title: ''},
			'⣜': {shift: 'ZZZ', decimal: '&#10460;', hex: '', title: ''},
			'⣝': {shift: 'ZZZ', decimal: '&#10461;', hex: '', title: ''},
			'⣞': {shift: 'ZZZ', decimal: '&#10462;', hex: '', title: ''},
			'⣟': {shift: 'ZZZ', decimal: '&#10463;', hex: '', title: ''},
			'⣠': {shift: 'ZZZ', decimal: '&#10464;', hex: '', title: ''},
			'⣡': {shift: 'ZZZ', decimal: '&#10465;', hex: '', title: ''},
			'⣢': {shift: 'ZZZ', decimal: '&#10466;', hex: '', title: ''},
			'⣣': {shift: 'ZZZ', decimal: '&#10467;', hex: '', title: ''},
			'⣤': {shift: 'ZZZ', decimal: '&#10468;', hex: '', title: ''},
			'⣥': {shift: 'ZZZ', decimal: '&#10469;', hex: '', title: ''},
			'⣦': {shift: 'ZZZ', decimal: '&#10470;', hex: '', title: ''},
			'⣧': {shift: 'ZZZ', decimal: '&#10471;', hex: '', title: ''},
			'⣨': {shift: 'ZZZ', decimal: '&#10472;', hex: '', title: ''},
			'⣩': {shift: 'ZZZ', decimal: '&#10473;', hex: '', title: ''},
			'⣪': {shift: 'ZZZ', decimal: '&#10474;', hex: '', title: ''},
			'⣫': {shift: 'ZZZ', decimal: '&#10475;', hex: '', title: ''},
			'⣬': {shift: 'ZZZ', decimal: '&#10476;', hex: '', title: ''},
			'⣭': {shift: 'ZZZ', decimal: '&#10477;', hex: '', title: ''},
			'⣮': {shift: 'ZZZ', decimal: '&#10478;', hex: '', title: ''},
			'⣯': {shift: 'ZZZ', decimal: '&#10479;', hex: '', title: ''},
			'⣰': {shift: 'ZZZ', decimal: '&#10480;', hex: '', title: ''},
			'⣱': {shift: 'ZZZ', decimal: '&#10481;', hex: '', title: ''},
			'⣲': {shift: 'ZZZ', decimal: '&#10482;', hex: '', title: ''},
			'⣳': {shift: 'ZZZ', decimal: '&#10483;', hex: '', title: ''},
			'⣴': {shift: 'ZZZ', decimal: '&#10484;', hex: '', title: ''},
			'⣵': {shift: 'ZZZ', decimal: '&#10485;', hex: '', title: ''},
			'⣶': {shift: 'ZZZ', decimal: '&#10486;', hex: '', title: ''},
			'⣷': {shift: 'ZZZ', decimal: '&#10487;', hex: '', title: ''},
			'⣸': {shift: 'ZZZ', decimal: '&#10488;', hex: '', title: ''},
			'⣹': {shift: 'ZZZ', decimal: '&#10489;', hex: '', title: ''},
			'⣺': {shift: 'ZZZ', decimal: '&#10490;', hex: '', title: ''},
			'⣻': {shift: 'ZZZ', decimal: '&#10491;', hex: '', title: ''},
			'⣼': {shift: 'ZZZ', decimal: '&#10492;', hex: '', title: ''},
			'⣽': {shift: 'ZZZ', decimal: '&#10493;', hex: '', title: ''},
			'⣾': {shift: 'ZZZ', decimal: '&#10494;', hex: '', title: ''},
			'⣿': {shift: 'ZZZ', decimal: '&#10495;', hex: '', title: ''}
		}

		this.allChars = {
			'İ': {shift: 'ZZZ', decimal: '&#304;', hex: '&#x130;', title: 'Capital I-dotted'},
			'ı': {shift: 'ZZZ', decimal: '&#305;', hex: '&#x131;', title: 'Lowercase i-dotless'},
			'Ö': {shift: 'ZZZ', decimal: '&#214;', hex: '&#xd6;', title: 'Capital O-umlaut'},
			'ö': {shift: 'ZZZ', decimal: '&#246;', hex: '&#xf6;', title: 'Lowercase o-umlaut'},
			'Ü': {shift: 'ZZZ', decimal: '&#220;', hex: '&#xdc;', title: 'Capital U-umlaut'},
			'ü': {shift: 'ZZZ', decimal: '&#252;', hex: '&#xfc;', title: 'Lowercase u-umlaut'},
			'Ç': {shift: 'ZZZ', decimal: '&#199;', hex: '&#xc7;', title: 'Capital C-cedil'},
			'ç': {shift: 'ZZZ', decimal: '&#231;', hex: '&#xe7;', title: 'Lowercase c-cedil'},
			'Ğ': {shift: 'ZZZ', decimal: '&#286;', hex: '&#x11e;', title: 'Capital G-breve'},
			'ğ': {shift: 'ZZZ', decimal: '&#287;', hex: '&#x11f;', title: 'Lowercase g-breve'},
			'Ş': {shift: 'ZZZ', decimal: '&#350;', hex: '&#x15e;', title: 'Capital S-cedil'},
			'ş': {shift: 'ZZZ', decimal: '&#351;', hex: '&#x15f;', title: 'Lowercase s-cedil'},
			'₤': {shift: 'ZZZ', decimal: '&#8356;', hex: '&#x20a4;', title: 'New Lir'},
			'Á': {shift: 'ZZZ', decimal: '&#193;', hex: '&#xc4;', title: 'Latin capital letter A with acute'},
			'á': {shift: 'ZZZ', decimal: '&#225;', hex: '&#xe1;', title: 'Latin small letter a with acute'},
			'É': {shift: 'ZZZ', decimal: '&#201;', hex: '&#xc9;', title: 'Latin capital letter E with acute'},
			'é': {shift: 'ZZZ', decimal: '&#233;', hex: '&#xe9;', title: 'Latin small letter e with acute'},
			'Í': {shift: 'ZZZ', decimal: '&#205;', hex: '&#xcd;', title: 'Latin capital letter I with acute'},
			'í': {shift: 'ZZZ', decimal: '&#237;', hex: '&#xed;', title: 'Latin small letter i with acute'},
			'Ñ': {shift: 'ZZZ', decimal: '&#209;', hex: '&#xd1;', title: 'Latin capital letter N with tilde'},
			'ñ': {shift: 'ZZZ', decimal: '&#241;', hex: '&#xf1;', title: 'Latin small letter n with tilde'},
			'Ó': {shift: 'ZZZ', decimal: '&#211;', hex: '&#xd3;', title: 'Latin capital letter O with acute'},
			'ó': {shift: 'ZZZ', decimal: '&#243;', hex: '&#xf3;', title: 'Latin small letter o with acute'},
			'Ú': {shift: 'ZZZ', decimal: '&#218;', hex: '&#xda;', title: 'Latin capital letter U with acute'},
			'ú': {shift: 'ZZZ', decimal: '&#250;', hex: '&#xfa;', title: 'Latin small letter u with acute'},
			'Ü': {shift: 'ZZZ', decimal: '&#220;', hex: '&#xdc;', title: 'Latin capital letter U with diaeresis'},
			'ü': {shift: 'ZZZ', decimal: '&#252;', hex: '&#xfc;', title: 'Latin small letter u with diaeresis'},
			'«': {shift: 'ZZZ', decimal: '&#171;', hex: '&#xab;', title: 'Left double angle quotes'},
			'»': {shift: 'ZZZ', decimal: '&#187;', hex: '&#xbb;', title: 'Right double angle quotes'},
			'¿': {shift: 'ZZZ', decimal: '&#191;', hex: '&#xbf;', title: 'Inverted question mark'},
			'¡': {shift: 'ZZZ', decimal: '&#161;', hex: '&#xa1;', title: 'Inverted exclamation mark'},
			'€': {shift: 'ZZZ', decimal: '&#128;', hex: '&#x80;', title: 'Euro sign'},
			'₧': {shift: 'ZZZ', decimal: '&#8359;', hex: '&#x20a7;', title: 'Peseta sign'},
			'А': {shift: 'ZZZ', decimal: '&#1040;', hex: '&#x410;', title: ''},
			'а': {shift: 'ZZZ', decimal: '&#1072;', hex: '&#x430;', title: ''},
			'Б': {shift: 'ZZZ', decimal: '&#1041;', hex: '&#x411;', title: ''},
			'б': {shift: 'ZZZ', decimal: '&#1073;', hex: '&#x431;', title: ''},
			'В': {shift: 'ZZZ', decimal: '&#1042;', hex: '&#x412;', title: ''},
			'в': {shift: 'ZZZ', decimal: '&#1074;', hex: '&#x432;', title: ''},
			'Г': {shift: 'ZZZ', decimal: '&#1043;', hex: '&#x413;', title: ''},
			'г': {shift: 'ZZZ', decimal: '&#1075;', hex: '&#x433;', title: ''},
			'Д': {shift: 'ZZZ', decimal: '&#1044;', hex: '&#x414;', title: ''},
			'д': {shift: 'ZZZ', decimal: '&#1076;', hex: '&#x434;', title: ''},
			'Е': {shift: 'ZZZ', decimal: '&#1045;', hex: '&#x415;', title: ''},
			'е': {shift: 'ZZZ', decimal: '&#1077;', hex: '&#x435;', title: ''},
			'Ж': {shift: 'ZZZ', decimal: '&#1046;', hex: '&#x416;', title: ''},
			'ж': {shift: 'ZZZ', decimal: '&#1078;', hex: '&#x436;', title: ''},
			'З': {shift: 'ZZZ', decimal: '&#1047;', hex: '&#x417;', title: ''},
			'з': {shift: 'ZZZ', decimal: '&#1079;', hex: '&#x437;', title: ''},
			'И': {shift: 'ZZZ', decimal: '&#1048;', hex: '&#x418;', title: ''},
			'и': {shift: 'ZZZ', decimal: '&#1080;', hex: '&#x438;', title: ''},
			'Й': {shift: 'ZZZ', decimal: '&#1049;', hex: '&#x419;', title: ''},
			'й': {shift: 'ZZZ', decimal: '&#1081;', hex: '&#x439;', title: ''},
			'К': {shift: 'ZZZ', decimal: '&#1050;', hex: '&#x41a;', title: ''},
			'к': {shift: 'ZZZ', decimal: '&#1082;', hex: '&#x43a;', title: ''},
			'Л': {shift: 'ZZZ', decimal: '&#1051;', hex: '&#x41b;', title: ''},
			'л': {shift: 'ZZZ', decimal: '&#1083;', hex: '&#x43b;', title: ''},
			'М': {shift: 'ZZZ', decimal: '&#1052;', hex: '&#x41c;', title: ''},
			'м': {shift: 'ZZZ', decimal: '&#1084;', hex: '&#x43c;', title: ''},
			'Н': {shift: 'ZZZ', decimal: '&#1053;', hex: '&#x41d;', title: ''},
			'н': {shift: 'ZZZ', decimal: '&#1085;', hex: '&#x43d;', title: ''},
			'О': {shift: 'ZZZ', decimal: '&#1054;', hex: '&#x41e;', title: ''},
			'о': {shift: 'ZZZ', decimal: '&#1086;', hex: '&#x43e;', title: ''},
			'П': {shift: 'ZZZ', decimal: '&#1055;', hex: '&#x41f;', title: ''},
			'п': {shift: 'ZZZ', decimal: '&#1087;', hex: '&#x43f;', title: ''},
			'Р': {shift: 'ZZZ', decimal: '&#1056;', hex: '&#x420;', title: ''},
			'р': {shift: 'ZZZ', decimal: '&#1088;', hex: '&#x440;', title: ''},
			'С': {shift: 'ZZZ', decimal: '&#1057;', hex: '&#x421;', title: ''},
			'с': {shift: 'ZZZ', decimal: '&#1089;', hex: '&#x441;', title: ''},
			'Т': {shift: 'ZZZ', decimal: '&#1058;', hex: '&#x422;', title: ''},
			'т': {shift: 'ZZZ', decimal: '&#1090;', hex: '&#x442;', title: ''},
			'У': {shift: 'ZZZ', decimal: '&#1059;', hex: '&#x423;', title: ''},
			'у': {shift: 'ZZZ', decimal: '&#1091;', hex: '&#x443;', title: ''},
			'Ф': {shift: 'ZZZ', decimal: '&#1060;', hex: '&#x424;', title: ''},
			'ф': {shift: 'ZZZ', decimal: '&#1092;', hex: '&#x444;', title: ''},
			'Х': {shift: 'ZZZ', decimal: '&#1061;', hex: '&#x425;', title: ''},
			'х': {shift: 'ZZZ', decimal: '&#1093;', hex: '&#x445;', title: ''},
			'Ц': {shift: 'ZZZ', decimal: '&#1062;', hex: '&#x426;', title: ''},
			'ц': {shift: 'ZZZ', decimal: '&#1094;', hex: '&#x446;', title: ''},
			'Ч': {shift: 'ZZZ', decimal: '&#1063;', hex: '&#x427;', title: ''},
			'ч': {shift: 'ZZZ', decimal: '&#1095;', hex: '&#x447;', title: ''},
			'Ш': {shift: 'ZZZ', decimal: '&#1064;', hex: '&#x428;', title: ''},
			'ш': {shift: 'ZZZ', decimal: '&#1096;', hex: '&#x448;', title: ''},
			'Щ': {shift: 'ZZZ', decimal: '&#1065;', hex: '&#x429;', title: ''},
			'щ': {shift: 'ZZZ', decimal: '&#1097;', hex: '&#x449;', title: ''},
			'Ъ': {shift: 'ZZZ', decimal: '&#1066;', hex: '&#x42a;', title: ''},
			'ъ': {shift: 'ZZZ', decimal: '&#1098;', hex: '&#x44a;', title: ''},
			'Ы': {shift: 'ZZZ', decimal: '&#1067;', hex: '&#x42b;', title: ''},
			'ы': {shift: 'ZZZ', decimal: '&#1099;', hex: '&#x44b;', title: ''},
			'Ь': {shift: 'ZZZ', decimal: '&#1068;', hex: '&#x42c;', title: ''},
			'ь': {shift: 'ZZZ', decimal: '&#1100;', hex: '&#x44c;', title: ''},
			'Э': {shift: 'ZZZ', decimal: '&#1069;', hex: '&#x42d;', title: ''},
			'э': {shift: 'ZZZ', decimal: '&#1101;', hex: '&#x44d;', title: ''},
			'Ю': {shift: 'ZZZ', decimal: '&#1070;', hex: '&#x42e;', title: ''},
			'ю': {shift: 'ZZZ', decimal: '&#1102;', hex: '&#x44e;', title: ''},
			'Я': {shift: 'ZZZ', decimal: '&#1071;', hex: '&#x42f;', title: ''},
			'я': {shift: 'ZZZ', decimal: '&#1103;', hex: '&#x44f;', title: ''},
			'Ă': {shift: 'ZZZ', decimal: '&#258;', hex: '&#x102;', title: 'Capital A-brev;'},
			'ă': {shift: 'ZZZ', decimal: '&#259;', hex: '&#x103;', title: 'Lowercase a-brev'},
			'Â': {shift: 'ZZZ', decimal: '&#194;', hex: '&#xc2;', title: 'Capital A-circumflex'},
			'â': {shift: 'ZZZ', decimal: '&#226;', hex: '&#xe2;', title: 'Lowercase a-circumflex'},
			'Î': {shift: 'ZZZ', decimal: '&#206;', hex: '&#xce;', title: 'Capital I-circumflex'},
			'î': {shift: 'ZZZ', decimal: '&#238;', hex: '&#xee;', title: 'Lowercase i-circumflex'},
			'Ș': {shift: 'ZZZ', decimal: '&#x218;', hex: '', title: 'Capital S-comm'},
			'ș': {shift: 'ZZZ', decimal: '&#x219;', hex: '', title: 'Lowercase s-comm'},
			'Ş': {shift: 'ZZZ', decimal: '&#350;', hex: '&#x15e;', title: 'Capital S-cedill'},
			'ş': {shift: 'ZZZ', decimal: '&#351;', hex: '&#x15f;', title: 'Lowercase s-cedill'},
			'Ț': {shift: 'ZZZ', decimal: '&#538;', hex: '&#x21a;', title: 'Capital T-comm'},
			'ț': {shift: 'ZZZ', decimal: '&#539;', hex: '&#x21b;', title: 'Lowercase t-comm'},
			'Ţ': {shift: 'ZZZ', decimal: '&#354;', hex: '&#x162;', title: 'Capital T-cedill'},
			'ţ': {shift: 'ZZZ', decimal: '&#355;', hex: '&#x163;', title: 'Lowercase t-cedill'},
			'Ą': {shift: 'ZZZ', decimal: '&#260;', hex: '&#x104;', title: 'Capital A-cedille'},
			'ą': {shift: 'ZZZ', decimal: '&#261;', hex: '&#x105;', title: 'Lowercase a-cedille'},
			'Ę': {shift: 'ZZZ', decimal: '&#280;', hex: '&#x118;', title: 'Capital E-cedille'},
			'ę': {shift: 'ZZZ', decimal: '&#281;', hex: '&#x119;', title: 'Lowercase e-cedille'},
			'Ó': {shift: 'ZZZ', decimal: '&#211;', hex: '&#xd3;', title: 'Capital O-acute'},
			'ó': {shift: 'ZZZ', decimal: '&#243;', hex: '&#xf3;', title: 'Lowercase o-acute'},
			'Ć': {shift: 'ZZZ', decimal: '&#262;', hex: '&#x106;', title: 'Capital C-acute'},
			'ć': {shift: 'ZZZ', decimal: '&#263;', hex: '&#x107;', title: 'Lowercase c-acute'},
			'Ł': {shift: 'ZZZ', decimal: '&#321;', hex: '&#x141;', title: 'Capital L-ba'},
			'ł': {shift: 'ZZZ', decimal: '&#322;', hex: '&#x142;', title: 'Lowercase l-bar'},
			'Ń': {shift: 'ZZZ', decimal: '&#323;', hex: '&#x143;', title: 'Capital N-acute'},
			'ń': {shift: 'ZZZ', decimal: '&#324;', hex: '&#x144;', title: 'Lowercase n-acute'},
			'Ś': {shift: 'ZZZ', decimal: '&#346;', hex: '&#x15a;', title: 'Capital S-acute'},
			'ś': {shift: 'ZZZ', decimal: '&#347;', hex: '&#x15b;', title: 'Lowercase s-acute'},
			'Ź': {shift: 'ZZZ', decimal: '&#377;', hex: '&#x179;', title: 'Capital Z-acute'},
			'ź': {shift: 'ZZZ', decimal: '&#378;', hex: '&#x17a;', title: 'Lowercase z-acute'},
			'Ż': {shift: 'ZZZ', decimal: '&#379;', hex: '&#x17b;', title: 'Capital Z-do'},
			'ż': {shift: 'ZZZ', decimal: '&#380;', hex: '&#x17c;', title: 'Lowercase z-dot'},
			'A': {shift: 'ZZZ', decimal: '&#65;', hex: '&#x41;', title: 'Uppercas'},
			'a': {shift: 'ZZZ', decimal: '&#97;', hex: '&#x61;', title: 'Lowercas'},
			'À': {shift: 'ZZZ', decimal: '&#192;', hex: '&#xC0;', title: 'Latin capital letter A with grav'},
			'à': {shift: 'ZZZ', decimal: '&#224;', hex: '&#xE0;', title: 'Latin small letter a with grav'},
			'Á': {shift: 'ZZZ', decimal: '&#193;', hex: '&#xC1;', title: 'Latin capital letter A with acut'},
			'á': {shift: 'ZZZ', decimal: '&#225;', hex: '&#xE1;', title: 'Latin small letter a with acut'},
			'Â': {shift: 'ZZZ', decimal: '&#194;', hex: '&#xC2;', title: 'Latin capital letter A with circumflex'},
			'â': {shift: 'ZZZ', decimal: '&#226;', hex: '&#xE2;', title: 'Latin small letter a with circumflex'},
			'Ã': {shift: 'ZZZ', decimal: '&#195;', hex: '&#xC3;', title: 'Latin capital letter A with tild'},
			'ã': {shift: 'ZZZ', decimal: '&#227;', hex: '&#xE3;', title: 'Latin small letter a with tild'},
			'ã': {shift: 'ZZZ', decimal: '&#227;', hex: '&#xE3;', title: 'Latin small letter a with tild'},
			'Ä': {shift: 'ZZZ', decimal: '&#196;', hex: '&#xC4;', title: 'Latin capital letter A with diaeresis'},
			'ä': {shift: 'ZZZ', decimal: '&#228;', hex: '&#xE4;', title: 'Latin small letter a with diaeresi'},
			'Å': {shift: 'ZZZ', decimal: '&#197;', hex: '&#xC5;', title: 'Latin capital letter A with ring above'},
			'å': {shift: 'ZZZ', decimal: '&#229;', hex: '&#xE5;', title: 'Latin small letter a with ring above'},
			'Æ': {shift: 'ZZZ', decimal: '&#198;', hex: '&#xC6;', title: 'Latin capital letter A'},
			'æ': {shift: 'ZZZ', decimal: '&#230;', hex: '&#xE6;', title: 'Latin small letter a'},
			'ª': {shift: 'ZZZ', decimal: '&#170;', hex: '&#xAA;', title: 'Feminine ordinal indicato'},
			'B': {shift: 'ZZZ', decimal: '&#66;', hex: '&#x42;', title: 'Uppercas'},
			'b': {shift: 'ZZZ', decimal: '&#98;', hex: '&#x62;', title: 'Lowercas'},
			'C': {shift: 'ZZZ', decimal: '&#67;', hex: '&#x43;', title: 'Uppercas'},
			'c': {shift: 'ZZZ', decimal: '&#99;', hex: '&#x63;', title: 'Lowercas'},
			'Ç': {shift: 'ZZZ', decimal: '&#199;', hex: '&#xC7;', title: 'Latin capital letter C with cedill'},
			'ç': {shift: 'ZZZ', decimal: '&#231;', hex: '&#xE7;', title: 'Latin small letter c with cedill'},
			'D': {shift: 'ZZZ', decimal: '&#68;', hex: '&#x44;', title: 'Uppercas'},
			'd': {shift: 'ZZZ', decimal: '&#100;', hex: '&#x64;', title: 'Lowercas'},
			'E': {shift: 'ZZZ', decimal: '&#69;', hex: '&#x45;', title: 'Uppercas'},
			'e': {shift: 'ZZZ', decimal: '&#101;', hex: '&#x65;', title: 'Lowercas'},
			'È': {shift: 'ZZZ', decimal: '&#200;', hex: '&#xC8;', title: 'Latin capital letter E with grav'},
			'è': {shift: 'ZZZ', decimal: '&#232;', hex: '&#xE8;', title: 'Latin small letter e with grav'},
			'É': {shift: 'ZZZ', decimal: '&#201;', hex: '&#xC9;', title: 'Latin capital letter E with acut'},
			'é': {shift: 'ZZZ', decimal: '&#233;', hex: '&#xE9;', title: 'Latin small letter e with acut'},
			'Ê': {shift: 'ZZZ', decimal: '&#202;', hex: '&#xCA;', title: 'Latin capital letter E with circumflex'},
			'ê': {shift: 'ZZZ', decimal: '&#234;', hex: '&#xEA;', title: 'Latin small letter e with circumflex'},
			'Ë': {shift: 'ZZZ', decimal: '&#203;', hex: '&#xCB;', title: 'Latin capital letter E with diaeresis'},
			'ë': {shift: 'ZZZ', decimal: '&#235;', hex: '&#xEB;', title: 'Latin small letter e with diaeresi'},
			'F': {shift: 'ZZZ', decimal: '&#70;', hex: '&#x46;', title: 'Uppercas'},
			'f': {shift: 'ZZZ', decimal: '&#102;', hex: '&#x66;', title: 'Lowercas'},
			'ƒ': {shift: 'ZZZ', decimal: '&#131;', hex: '&#x83;', title: 'Latin small letter f with hoo'},
			'G': {shift: 'ZZZ', decimal: '&#71;', hex: '&#x47;', title: 'Uppercas'},
			'g': {shift: 'ZZZ', decimal: '&#103;', hex: '&#x67;', title: 'Lowercas'},
			'H': {shift: 'ZZZ', decimal: '&#72;', hex: '&#x48;', title: 'Uppercas'},
			'h': {shift: 'ZZZ', decimal: '&#104;', hex: '&#x68;', title: 'Lowercas'},
			'I': {shift: 'ZZZ', decimal: '&#73;', hex: '&#x49;', title: 'Uppercas'},
			'i': {shift: 'ZZZ', decimal: '&#105;', hex: '&#x69;', title: 'Lowercas'},
			'Ì': {shift: 'ZZZ', decimal: '&#204;', hex: '&#xCC;', title: 'Latin capital letter I with grav'},
			'ì': {shift: 'ZZZ', decimal: '&#236;', hex: '&#xEC;', title: 'Latin small letter i with grav'},
			'Í': {shift: 'ZZZ', decimal: '&#205;', hex: '&#xCD;', title: 'Latin capital letter I with acut'},
			'í': {shift: 'ZZZ', decimal: '&#237;', hex: '&#xED;', title: 'Latin small letter i with acut'},
			'Î': {shift: 'ZZZ', decimal: '&#206;', hex: '&#xCE;', title: 'Latin capital letter I with circumflex'},
			'î': {shift: 'ZZZ', decimal: '&#238;', hex: '&#xEE;', title: 'Latin small letter i with circumflex'},
			'Ï': {shift: 'ZZZ', decimal: '&#207;', hex: '&#xCF;', title: 'Latin capital letter I with diaeresis'},
			'ï': {shift: 'ZZZ', decimal: '&#239;', hex: '&#xEF;', title: 'Latin small letter i with diaeresi'},
			'J': {shift: 'ZZZ', decimal: '&#74;', hex: '&#x4A;', title: 'Uppercas'},
			'j': {shift: 'ZZZ', decimal: '&#106;', hex: '&#x6A;', title: 'Lowercas'},
			'K': {shift: 'ZZZ', decimal: '&#75;', hex: '&#x4B;', title: 'Uppercas'},
			'k': {shift: 'ZZZ', decimal: '&#107;', hex: '&#x6B;', title: 'Lowercas'},
			'L': {shift: 'ZZZ', decimal: '&#76;', hex: '&#x4C;', title: 'Uppercas'},
			'l': {shift: 'ZZZ', decimal: '&#108;', hex: '&#x6C;', title: 'Lowercas'},
			'M': {shift: 'ZZZ', decimal: '&#77;', hex: '&#x4D;', title: 'Uppercas'},
			'm': {shift: 'ZZZ', decimal: '&#109;', hex: '&#x6D;', title: 'Lowercas'},
			'N': {shift: 'ZZZ', decimal: '&#78;', hex: '&#x4E;', title: 'Uppercas'},
			'n': {shift: 'ZZZ', decimal: '&#110;', hex: '&#x6E;', title: 'Lowercas'},
			'Ñ': {shift: 'ZZZ', decimal: '&#209;', hex: '&#xD1;', title: 'Latin capital letter N with tild'},
			'ñ': {shift: 'ZZZ', decimal: '&#241;', hex: '&#xF1;', title: 'Latin small letter n with tild'},
			'O': {shift: 'ZZZ', decimal: '&#79;', hex: '&#x4F;', title: 'Uppercas'},
			'o': {shift: 'ZZZ', decimal: '&#111;', hex: '&#x6F;', title: 'Lowercas'},
			'Ò': {shift: 'ZZZ', decimal: '&#210;', hex: '&#xD2;', title: 'Latin capital letter O with grav'},
			'ò': {shift: 'ZZZ', decimal: '&#242;', hex: '&#xF2;', title: 'Latin small letter o with grav'},
			'Ó': {shift: 'ZZZ', decimal: '&#211;', hex: '&#xD3;', title: 'Latin capital letter O with acut'},
			'ó': {shift: 'ZZZ', decimal: '&#243;', hex: '&#xF3;', title: 'Latin small letter o with acut'},
			'Ô': {shift: 'ZZZ', decimal: '&#212;', hex: '&#xD4;', title: 'Latin capital letter O with circumflex'},
			'ô': {shift: 'ZZZ', decimal: '&#244;', hex: '&#xF4;', title: 'Latin small letter o with circumflex'},
			'Õ': {shift: 'ZZZ', decimal: '&#213;', hex: '&#xD5;', title: 'Latin capital letter O with tild'},
			'õ': {shift: 'ZZZ', decimal: '&#245;', hex: '&#xF5;', title: 'Latin small letter o with tild'},
			'Ö': {shift: 'ZZZ', decimal: '&#214;', hex: '&#xD6;', title: 'Latin capital letter O with diaeresis'},
			'ö': {shift: 'ZZZ', decimal: '&#246;', hex: '&#xF6;', title: 'Latin small letter o with diaeresi'},
			'Ø': {shift: 'ZZZ', decimal: '&#216;', hex: '&#xD8;', title: 'Latin capital letter O with slash'},
			'ø': {shift: 'ZZZ', decimal: '&#248;', hex: '&#xF8;', title: 'Latin small letter o with slash'},
			'P': {shift: 'ZZZ', decimal: '&#80;', hex: '&#x50;', title: 'Uppercase'},
			'p': {shift: 'ZZZ', decimal: '&#112;', hex: '&#x70;', title: 'Lowercase'},
			'Q': {shift: 'ZZZ', decimal: '&#81;', hex: '&#x51;', title: 'Uppercase'},
			'q': {shift: 'ZZZ', decimal: '&#113;', hex: '&#x71;', title: 'Lowercase'},
			'R': {shift: 'ZZZ', decimal: '&#82;', hex: '&#x52;', title: 'Uppercase'},
			'r': {shift: 'ZZZ', decimal: '&#114;', hex: '&#x72;', title: 'Lowercase'},
			'S': {shift: 'ZZZ', decimal: '&#83;', hex: '&#x53;', title: 'Uppercase'},
			's': {shift: 'ZZZ', decimal: '&#115;', hex: '&#x73;', title: 'Lowercas'},
			'Š': {shift: 'ZZZ', decimal: '&#138;', hex: '&#x8A;', title: 'Latin capital letter S with caro'},
			'š': {shift: 'ZZZ', decimal: '&#154;', hex: '&#x9A;', title: 'Latin small letter S with caro'},
			'ß': {shift: 'ZZZ', decimal: '&#223;', hex: '&#xDF;', title: 'Latin small letter sharp s - ess-zed'},
			'T': {shift: 'ZZZ', decimal: '&#84;', hex: '&#x54;', title: 'Uppercase'},
			't': {shift: 'ZZZ', decimal: '&#116;', hex: '&#x74;', title: 'Lowercase'},
			'U': {shift: 'ZZZ', decimal: '&#85;', hex: '&#x55;', title: 'Uppercase'},
			'u': {shift: 'ZZZ', decimal: '&#117;', hex: '&#x75;', title: 'Lowercase'},
			'Ù': {shift: 'ZZZ', decimal: '&#217;', hex: '&#xD9;', title: 'Latin capital letter U with grave'},
			'ù': {shift: 'ZZZ', decimal: '&#249;', hex: '&#xF9;', title: 'Latin small letter u with grave'},
			'Ú': {shift: 'ZZZ', decimal: '&#218;', hex: '&#xDA;', title: 'Latin capital letter U with acute'},
			'ú': {shift: 'ZZZ', decimal: '&#250;', hex: '&#xFA;', title: 'Latin small letter u with acute'},
			'Û': {shift: 'ZZZ', decimal: '&#219;', hex: '&#xDB;', title: 'Latin capital letter U with circumflex'},
			'û': {shift: 'ZZZ', decimal: '&#251;', hex: '&#xFB;', title: 'Latin small letter u with circumflex'},
			'Ü': {shift: 'ZZZ', decimal: '&#220;', hex: '&#xDC;', title: 'Latin capital letter U with diaeresis'},
			'ü': {shift: 'ZZZ', decimal: '&#252;', hex: '&#xFC;', title: 'Latin small letter u with diaeresi'},
			'Ü': {shift: 'ZZZ', decimal: '&#220;', hex: '&#xDC;', title: 'Latin capital letter U with diaeresis'},
			'ü': {shift: 'ZZZ', decimal: '&#252;', hex: '&#xFC;', title: 'Latin small letter u with diaeresis'},
			'V': {shift: 'ZZZ', decimal: '&#86;', hex: '&#x56;', title: 'Uppercas'},
			'v': {shift: 'ZZZ', decimal: '&#118;', hex: '&#x76;', title: 'Lowercas'},
			'W': {shift: 'ZZZ', decimal: '&#87;', hex: '&#x57;', title: 'Uppercas'},
			'w': {shift: 'ZZZ', decimal: '&#119;', hex: '&#x77;', title: 'Lowercas'},
			'X': {shift: 'ZZZ', decimal: '&#88;', hex: '&#x58;', title: 'Uppercas'},
			'x': {shift: 'ZZZ', decimal: '&#120;', hex: '&#x78;', title: 'Lowercas'},
			'Y': {shift: 'ZZZ', decimal: '&#89;', hex: '&#x59;', title: 'Uppercas'},
			'y': {shift: 'ZZZ', decimal: '&#121;', hex: '&#x79;', title: 'Lowercas'},
			'Ÿ': {shift: 'ZZZ', decimal: '&#159;', hex: '&#x9F;', title: 'Latin capital letter Y with diaeresis'},
			'ÿ': {shift: 'ZZZ', decimal: '&#255;', hex: '&#xFF;', title: 'Latin small letter y with diaeresis'},
			'Ý': {shift: 'ZZZ', decimal: '&#221;', hex: '&#xDD;', title: 'Latin capital letter Y with acute'},
			'ý': {shift: 'ZZZ', decimal: '&#253;', hex: '&#xFD;', title: 'Latin small letter y with acute'},
			'Z': {shift: 'ZZZ', decimal: '&#90;', hex: '&#x5A;', title: 'Uppercase'},
			'z': {shift: 'ZZZ', decimal: '&#122;', hex: '&#x7A;', title: 'Lowercase'},
			'Ž': {shift: 'ZZZ', decimal: '&#142;', hex: '&#x8E;', title: 'Latin captial letter Z with caro'},
			'ž': {shift: 'ZZZ', decimal: '&#158;', hex: '&#x9E;', title: 'Latin small letter z with caro'},
			'0': {shift: 'ZZZ', decimal: '&#48;', hex: '&#x30;', title: 'Zero'},
			'1': {shift: 'ZZZ', decimal: '&#49;', hex: '&#x31;', title: 'One'},
			'2': {shift: 'ZZZ', decimal: '&#50;', hex: '&#x32;', title: 'Two'},
			'3': {shift: 'ZZZ', decimal: '&#51;', hex: '&#x33;', title: 'Three'},
			'4': {shift: 'ZZZ', decimal: '&#52;', hex: '&#x34;', title: 'Four'},
			'5': {shift: 'ZZZ', decimal: '&#53;', hex: '&#x35;', title: 'Five'},
			'6': {shift: 'ZZZ', decimal: '&#54;', hex: '&#x36;', title: 'Six'},
			'7': {shift: 'ZZZ', decimal: '&#55;', hex: '&#x37;', title: 'Seven'},
			'8': {shift: 'ZZZ', decimal: '&#56;', hex: '&#x38;', title: 'Eight'},
			'9': {shift: 'ZZZ', decimal: '&#57;', hex: '&#x39;', title: 'Nine'},
			'¼': {shift: 'ZZZ', decimal: '&#188;', hex: '&#xBC;', title: 'Fraction one quarter'},
			'½': {shift: 'ZZZ', decimal: '&#189;', hex: '&#xBD;', title: 'Fraction one half'},
			'¾': {shift: 'ZZZ', decimal: '&#190;', hex: '&#xBE;', title: 'Fraction three quarter'},
			'¹': {shift: 'ZZZ', decimal: '&#185;', hex: '&#xB9;', title: 'Superscript on'},
			'²': {shift: 'ZZZ', decimal: '&#178;', hex: '&#xB2;', title: 'Superscript two - square'},
			'³': {shift: 'ZZZ', decimal: '&#179;', hex: '&#xB3;', title: 'Superscript three - cube'},
			'°': {shift: 'ZZZ', decimal: '&#176;', hex: '&#xB0;', title: 'Degree sign'},
			' ': {shift: 'ZZZ', decimal: '&#32;', hex: '&#x20;', title: 'Space'},
			'!': {shift: 'ZZZ', decimal: '&#33;', hex: '&#x21;', title: 'Exclamation mark'},
			'¡': {shift: 'ZZZ', decimal: '&#161;', hex: '&#xA1;', title: 'Inverted exclamation mark'},
			'#': {shift: 'ZZZ', decimal: '&#35;', hex: '&#x23;', title: 'Numbe'},
			'&': {shift: 'ZZZ', decimal: '&#38;', hex: '&#x26;', title: 'Ampersan'},
			'*': {shift: 'ZZZ', decimal: '&#42;', hex: '&#x2A;', title: 'Asteris'},
			',': {shift: 'ZZZ', decimal: '&#44;', hex: '&#x2C;', title: 'Comm'},
			'-': {shift: 'ZZZ', decimal: '&#45;', hex: '&#x2D;', title: 'Hyphe'},
			'.': {shift: 'ZZZ', decimal: '&#46;', hex: '&#x2E;', title: 'Period, dot or full stop'},
			'~': {shift: 'ZZZ', decimal: '&#126;', hex: '&#x7E;', title: 'Equivalency sign - tild'},
			'/': {shift: 'ZZZ', decimal: '&#47;', hex: '&#x2F;', title: 'Slash or divid'},

      /* had to escape baskslash / => // */
			'\\': {shift: 'ZZZ', decimal: '&#92;', hex: '&#x5C;', title: 'Reverse solidus / Backslash'},
			':': {shift: 'ZZZ', decimal: '&#58;', hex: '&#x3A;', title: 'Colo'},
			';': {shift: 'ZZZ', decimal: '&#59;', hex: '&#x3B;', title: 'Semicolo'},
			'?': {shift: 'ZZZ', decimal: '&#63;', hex: '&#x3F;', title: 'Question mar'},
			'¿': {shift: 'ZZZ', decimal: '&#191;', hex: '&#xBF;', title: 'Inverted question mar'},
			'@': {shift: 'ZZZ', decimal: '&#64;', hex: '&#x40;', title: 'At symbo'},
			'(': {shift: 'ZZZ', decimal: '&#40;', hex: '&#x28;', title: 'Open parenthesis (or open bracket) '},
			')': {shift: 'ZZZ', decimal: '&#41;', hex: '&#x29;', title: 'Close parenthesis (or close bracket)'},
			'[': {shift: 'ZZZ', decimal: '&#91;', hex: '&#x5B;', title: 'Opening bracke'},
			']': {shift: 'ZZZ', decimal: '&#93;', hex: '&#x5D;', title: 'Closing bracke'},
			'{': {shift: 'ZZZ', decimal: '&#123;', hex: '&#x7B;', title: 'Opening brac'},
			'}': {shift: 'ZZZ', decimal: '&#125;', hex: '&#x7D;', title: 'Closing brac'},
			'|': {shift: 'ZZZ', decimal: '&#124;', hex: '&#x7C;', title: 'Vertical ba'},
			'¦': {shift: 'ZZZ', decimal: '&#166;', hex: '&#xA6;', title: 'Pipe, Broken vertical ba'},
			'•': {shift: 'ZZZ', decimal: '&#149;', hex: '&#x95;', title: 'Bulle'},
			'–': {shift: 'ZZZ', decimal: '&#150;', hex: '&#x96;', title: 'En das'},
			'—': {shift: 'ZZZ', decimal: '&#151;', hex: '&#x97;', title: 'Em das'},
			'_': {shift: 'ZZZ', decimal: '&#95;', hex: '&#x5F;', title: 'Underscor'},
			'': {shift: 'ZZZ', decimal: '&#127;', hex: '&#x7F;', title: 'Delet'},
			'™': {shift: 'ZZZ', decimal: '&#153;', hex: '&#x99;', title: 'Trade mark sig'},
			'©': {shift: 'ZZZ', decimal: '&#169;', hex: '&#xA9;', title: 'Copyright sig'},
			'®': {shift: 'ZZZ', decimal: '&#174;', hex: '&#xAE;', title: 'Registered trade mark sig'},
			'$': {shift: 'ZZZ', decimal: '&#36;', hex: '&#x24;', title: 'Dolla'},
			'€': {shift: 'ZZZ', decimal: '&#128;', hex: '&#x80;', title: 'Euro sig'},
			'¢': {shift: 'ZZZ', decimal: '&#162;', hex: '&#xA2;', title: 'Cent sig'},
			'£': {shift: 'ZZZ', decimal: '&#163;', hex: '&#xA3;', title: 'Pound sig'},
			'¤': {shift: 'ZZZ', decimal: '&#164;', hex: '&#xA4;', title: 'Currency sig'},
			'¥': {shift: 'ZZZ', decimal: '&#165;', hex: '&#xA5;', title: 'Yen sig'},

			/* escape */
			'\'': {shift: 'ZZZ', decimal: '&#39;', hex: '&#x27;', title: 'Single quot'},
			'"': {shift: 'ZZZ', decimal: '&#34;', hex: '&#x22;', title: 'Double quotes (or speech marks) '},
			'‘': {shift: 'ZZZ', decimal: '&#145;', hex: '&#x91;', title: 'Left single quotation mar'},
			'’': {shift: 'ZZZ', decimal: '&#146;', hex: '&#x92;', title: 'Right single quotation mar'},
			'“': {shift: 'ZZZ', decimal: '&#147;', hex: '&#x93;', title: 'Left double quotation mar'},
			'”': {shift: 'ZZZ', decimal: '&#148;', hex: '&#x94;', title: 'Right double quotation mar'},
			'`': {shift: 'ZZZ', decimal: '&#96;', hex: '&#x60;', title: 'Grave accen'},
			'´': {shift: 'ZZZ', decimal: '&#180;', hex: '&#xB4;', title: 'Acute accent - spacing acut'},
			'˜': {shift: 'ZZZ', decimal: '&#152;', hex: '&#x98;', title: 'Small tild'},
			'^': {shift: 'ZZZ', decimal: '&#94;', hex: '&#x5E;', title: 'Caret - circumfle'},
			'ˆ': {shift: 'ZZZ', decimal: '&#136;', hex: '&#x88;', title: 'Modifier letter circumflex accen'},
			'‹': {shift: 'ZZZ', decimal: '&#139;', hex: '&#x8B;', title: 'Single left-pointing angle quotation'},
			'›': {shift: 'ZZZ', decimal: '&#155;', hex: '&#x9B;', title: 'Single right-pointing angle quotation mark'},
			'«': {shift: 'ZZZ', decimal: '&#171;', hex: '&#xAB;', title: 'Left double angle quote'},
			'»': {shift: 'ZZZ', decimal: '&#187;', hex: '&#xBB;', title: 'Right double angle quote'},
			'<': {shift: 'ZZZ', decimal: '&#60;', hex: '&#x3C;', title: 'Less than (or open angled bracket) '},
			'>': {shift: 'ZZZ', decimal: '&#62;', hex: '&#x3E;', title: 'Greater than (or close angled bracket)'},
			'%': {shift: 'ZZZ', decimal: '&#37;', hex: '&#x25;', title: 'Procenttecke'},
			'=': {shift: 'ZZZ', decimal: '&#61;', hex: '&#x3D;', title: 'Equal'},
			'+': {shift: 'ZZZ', decimal: '&#43;', hex: '&#x2B;', title: 'Plu'},
			'×': {shift: 'ZZZ', decimal: '&#215;', hex: '&#xD7;', title: 'Multiplication sig'},
			'÷': {shift: 'ZZZ', decimal: '&#247;', hex: '&#xF7;', title: 'Division sig'},
			'±': {shift: 'ZZZ', decimal: '&#177;', hex: '&#xB1;', title: 'Plus-or-minus sig'},
			'‚': {shift: 'ZZZ', decimal: '&#130;', hex: '&#x82;', title: 'Single low-9 quotation mar'},
			'„': {shift: 'ZZZ', decimal: '&#132;', hex: '&#x84;', title: 'Double low-9 quotation mar'},
			'…': {shift: 'ZZZ', decimal: '&#133;', hex: '&#x85;', title: 'Horizontal ellipsi'},
			'†': {shift: 'ZZZ', decimal: '&#134;', hex: '&#x86;', title: 'Dagge'},
			'‡': {shift: 'ZZZ', decimal: '&#135;', hex: '&#x87;', title: 'Double dagge'},
			'‰': {shift: 'ZZZ', decimal: '&#137;', hex: '&#x89;', title: 'Per mille sig'},
			'Œ': {shift: 'ZZZ', decimal: '&#338;', hex: '&#x8C;', title: 'Latin capital ligature O'},
			'œ': {shift: 'ZZZ', decimal: '&#339;', hex: '&#x9C;', title: 'Latin small ligature o'},
			'§': {shift: 'ZZZ', decimal: '&#167;', hex: '&#xA7;', title: 'Section sig'},
			'¨': {shift: 'ZZZ', decimal: '&#168;', hex: '&#xA8;', title: 'Spacing diaeresis - umlau'},
			'¬': {shift: 'ZZZ', decimal: '&#172;', hex: '&#xAC;', title: 'Not sig'},
			'µ': {shift: 'ZZZ', decimal: '&#181;', hex: '&#xB5;', title: 'Micro sig'},
			'¶': {shift: 'ZZZ', decimal: '&#182;', hex: '&#xB6;', title: 'Pilcrow sign - paragraph sig'},
			'·': {shift: 'ZZZ', decimal: '&#183;', hex: '&#xB7;', title: 'Middle dot - Georgian comm'},
			'¸': {shift: 'ZZZ', decimal: '&#184;', hex: '&#xB8;', title: 'Spacing cedill'},
			'º': {shift: 'ZZZ', decimal: '&#186;', hex: '&#xBA;', title: 'Masculine ordinal indicato'},
			'Ð': {shift: 'ZZZ', decimal: '&#208;', hex: '&#xD0;', title: 'Latin capital letter ET'},
			'Þ': {shift: 'ZZZ', decimal: '&#222;', hex: '&#xDE;', title: 'Latin capital letter THOR'},
			'ð': {shift: 'ZZZ', decimal: '&#240;', hex: '&#xF0;', title: 'Latin small letter et'},
			'þ': {shift: 'ZZZ', decimal: '&#254;', hex: '&#xFE;', title: 'Latin small letter thor'},
			'Ä': {shift: 'ZZZ', decimal: '&#196;', hex: '&#xc4;', title: 'Capital A-umlaut'},
			'ä': {shift: 'ZZZ', decimal: '&#228;', hex: '&#xe4;', title: 'Lowercase a-umlaut'},
			'Ē': {shift: 'ZZZ', decimal: '&#274;', hex: '&#x112;', title: 'Capital E-umlaut'},
			'ē': {shift: 'ZZZ', decimal: '&#275;', hex: '&#x113;', title: 'Lowercase e-umlaut'},
			'Ī': {shift: 'ZZZ', decimal: '&#298;', hex: '&#x12a;', title: 'Capital I-umlaut'},
			'ī': {shift: 'ZZZ', decimal: '&#299;', hex: '&#x12b;', title: 'Lowercase i-umlaut'},
			'Ō': {shift: 'ZZZ', decimal: '&#332;', hex: '&#x14c;', title: 'Capital O-umlaut'},
			'ō': {shift: 'ZZZ', decimal: '&#333;', hex: '&#x14d;', title: 'Lowercase o-umlaut'},
			'Ū': {shift: 'ZZZ', decimal: '&#362;', hex: '&#x16a;', title: 'Capital U-umlaut'},
			'ū': {shift: 'ZZZ', decimal: '&#363;', hex: '&#x16b;', title: 'Lowercase u-umlaut'},
			'ʻ': {shift: 'ZZZ', decimal: '&#699;', hex: '&#x2bb;', title: 'Lowercase y-umlaut'},
			'Α': {shift: 'ZZZ', decimal: '&#913;', hex: '&#x391;', title: 'Capital Alpha'},
			'α': {shift: 'ZZZ', decimal: '&#945;', hex: '&#x3b1;', title: 'Lowercase Alpha'},
			'Β': {shift: 'ZZZ', decimal: '&#914;', hex: '&#x392;', title: 'Capital Bet'},
			'β': {shift: 'ZZZ', decimal: '&#946;', hex: '&#x3b2;', title: 'Lowercase Beta'},
			'Γ': {shift: 'ZZZ', decimal: '&#915;', hex: '&#x393;', title: 'Capital Gamma'},
			'γ': {shift: 'ZZZ', decimal: '&#947;', hex: '&#x3b3;', title: 'Lowercase Gamma'},
			'Δ': {shift: 'ZZZ', decimal: '&#916;', hex: '&#x394;', title: 'Capital Delta'},
			'δ': {shift: 'ZZZ', decimal: '&#948;', hex: '&#x3b4;', title: 'Lowercase Delta'},
			'Ε': {shift: 'ZZZ', decimal: '&#917;', hex: '&#x395;', title: 'Capital Epsilon'},
			'ε': {shift: 'ZZZ', decimal: '&#949;', hex: '&#x3b5;', title: 'Lowercase Epsilon'},
			'Ζ': {shift: 'ZZZ', decimal: '&#918;', hex: '&#x396;', title: 'Capital Zet'},
			'ζ': {shift: 'ZZZ', decimal: '&#950;', hex: '&#x3b6;', title: 'Lowercase Zeta'},
			'Η': {shift: 'ZZZ', decimal: '&#919;', hex: '&#x397;', title: 'Capital Et'},
			'η': {shift: 'ZZZ', decimal: '&#951;', hex: '&#x3b7;', title: 'Lowercase Eta'},
			'Θ': {shift: 'ZZZ', decimal: '&#920;', hex: '&#x398;', title: 'Capital Theta'},
			'θ': {shift: 'ZZZ', decimal: '&#952;', hex: '&#x3b8;', title: 'Lowercase Theta'},
			'Ι': {shift: 'ZZZ', decimal: '&#921;', hex: '&#x399;', title: 'Capital Iot'},
			'ι': {shift: 'ZZZ', decimal: '&#953;', hex: '&#x3b9;', title: 'Lowercase Iota'},
			'Κ': {shift: 'ZZZ', decimal: '&#922;', hex: '&#x39a;', title: 'Capital Kappa'},
			'κ': {shift: 'ZZZ', decimal: '&#954;', hex: '&#x3ba;', title: 'Lowercase Kappa'},
			'Λ': {shift: 'ZZZ', decimal: '&#923;', hex: '&#x39b;', title: 'Capital Lambda'},
			'λ': {shift: 'ZZZ', decimal: '&#955;', hex: '&#x3bb;', title: 'Lowercase Lambda'},
			'Μ': {shift: 'ZZZ', decimal: '&#924;', hex: '&#x39c;', title: 'Capital M'},
			'μ': {shift: 'ZZZ', decimal: '&#956;', hex: '&#x3bc;', title: 'Lowercase M'},
			'Ν': {shift: 'ZZZ', decimal: '&#925;', hex: '&#x39d;', title: 'Capital N'},
			'ν': {shift: 'ZZZ', decimal: '&#957;', hex: '&#x3bd;', title: 'Lowercase N'},
			'Ξ': {shift: 'ZZZ', decimal: '&#926;', hex: '&#x39e;', title: 'Capital X'},
			'ξ': {shift: 'ZZZ', decimal: '&#958;', hex: '&#x3be;', title: 'Lowercase X'},
			'Ο': {shift: 'ZZZ', decimal: '&#927;', hex: '&#x39f;', title: 'Capital Omicron'},
			'ο': {shift: 'ZZZ', decimal: '&#959;', hex: '&#x3bf;', title: 'Lowercase Omicron'},
			'Π': {shift: 'ZZZ', decimal: '&#928;', hex: '&#x3a0;', title: 'Capital P'},
			'π': {shift: 'ZZZ', decimal: '&#960;', hex: '&#x3c0;', title: 'Lowercase P'},
			'Ρ': {shift: 'ZZZ', decimal: '&#929;', hex: '&#x3a1;', title: 'Capital Rh'},
			'ρ': {shift: 'ZZZ', decimal: '&#961;', hex: '&#x3c1;', title: 'Lowercase Rho'},
			'Σ': {shift: 'ZZZ', decimal: '&#931;', hex: '&#x3a3;', title: 'Capital Sigma'},
			'σ': {shift: 'ZZZ', decimal: '&#963;', hex: '&#x3c3;', title: 'Lowercase Sigma'},
			'Σ': {shift: 'ZZZ', decimal: '&#931;', hex: '&#x3a3;', title: 'Capital Sigma'},
			'σ': {shift: 'ZZZ', decimal: '&#963;', hex: '&#x3c3;', title: 'Lowercase Sigma'},
			'ς': {shift: 'ZZZ', decimal: '&#962;', hex: '&#x3c2;', title: 'Lowercase Final Sigma'},
			'Τ': {shift: 'ZZZ', decimal: '&#932;', hex: '&#x3a4;', title: 'Capital Ta'},
			'τ': {shift: 'ZZZ', decimal: '&#964;', hex: '&#x3c4;', title: 'Lowercase Tau'},
			'Υ': {shift: 'ZZZ', decimal: '&#933;', hex: '&#x3a5;', title: 'Capital Upsilon'},
			'υ': {shift: 'ZZZ', decimal: '&#965;', hex: '&#x3c5;', title: 'Lowercase Upsilon'},
			'Φ': {shift: 'ZZZ', decimal: '&#934;', hex: '&#x3a6;', title: 'Capital Ph'},
			'φ': {shift: 'ZZZ', decimal: '&#966;', hex: '&#x3c6;', title: 'Lowercase Phi'},
			'Χ': {shift: 'ZZZ', decimal: '&#935;', hex: '&#x3a7;', title: 'Capital Ch'},
			'χ': {shift: 'ZZZ', decimal: '&#967;', hex: '&#x3c7;', title: 'Lowercase Chi'},
			'Ψ': {shift: 'ZZZ', decimal: '&#936;', hex: '&#x3a8;', title: 'Capital Ps'},
			'ψ': {shift: 'ZZZ', decimal: '&#968;', hex: '&#x3c8;', title: 'Lowercase Psi'},
			'Ω': {shift: 'ZZZ', decimal: '&#937;', hex: '&#x3a9;', title: 'Capital Omega'},
			'ω': {shift: 'ZZZ', decimal: '&#969;', hex: '&#x3c9;', title: 'Lowercase Omega'},
			'À': {shift: 'ZZZ', decimal: '&#192;', hex: '&#xc0;', title: 'Capital A-grave'},
			'à': {shift: 'ZZZ', decimal: '&#224;', hex: '&#xe0;', title: 'Lowercase a-grave'},
			'Â': {shift: 'ZZZ', decimal: '&#194;', hex: '&#xc2;', title: 'Capital A-circumflex'},
			'â': {shift: 'ZZZ', decimal: '&#226;', hex: '&#xe2;', title: 'Lowercase a-circumflex'},
			'Æ': {shift: 'ZZZ', decimal: '&#198;', hex: '&#xc6;', title: 'Capital AE Ligature'},
			'æ': {shift: 'ZZZ', decimal: '&#230;', hex: '&#xe6;', title: 'Lowercase AE Ligature'},
			'Ç': {shift: 'ZZZ', decimal: '&#199;', hex: '&#xc7;', title: 'Capital C-cedilla'},
			'ç': {shift: 'ZZZ', decimal: '&#231;', hex: '&#xe7;', title: 'Lowercase c-cedilla'},
			'È': {shift: 'ZZZ', decimal: '&#200;', hex: '&#xc8;', title: 'Capital E-grave'},
			'è': {shift: 'ZZZ', decimal: '&#232;', hex: '&#xe8;', title: 'Lowercase e-grave'},
			'É': {shift: 'ZZZ', decimal: '&#201;', hex: '&#xc9;', title: 'Capital E-acute'},
			'é': {shift: 'ZZZ', decimal: '&#233;', hex: '&#xe9;', title: 'Lowercase e-acute'},
			'Ê': {shift: 'ZZZ', decimal: '&#202;', hex: '&#xca;', title: 'Capital E-circumflex'},
			'ê': {shift: 'ZZZ', decimal: '&#234;', hex: '&#xea;', title: 'Lowercase e-circumflex'},
			'Ë': {shift: 'ZZZ', decimal: '&#203;', hex: '&#xcb;', title: 'Capital E-umlaut'},
			'ë': {shift: 'ZZZ', decimal: '&#235;', hex: '&#xeb;', title: 'Lowercase e-umlaut'},
			'Î': {shift: 'ZZZ', decimal: '&#206;', hex: '&#xce;', title: 'Capital I-circumflex'},
			'î': {shift: 'ZZZ', decimal: '&#238;', hex: '&#xee;', title: 'Lowercase i-circumflex'},
			'Ï': {shift: 'ZZZ', decimal: '&#207;', hex: '&#xcf;', title: 'Capital I-umlaut'},
			'ï': {shift: 'ZZZ', decimal: '&#239;', hex: '&#xef;', title: 'Lowercase i-umlaut'},
			'Ô': {shift: 'ZZZ', decimal: '&#212;', hex: '&#xd4;', title: 'Capital O-circumflex'},
			'ô': {shift: 'ZZZ', decimal: '&#244;', hex: '&#xf4;', title: 'Lowercase o-circumflex'},
			'Œ': {shift: 'ZZZ', decimal: '&#140;', hex: '&#x8c;', title: 'Capital OE ligature'},
			'œ': {shift: 'ZZZ', decimal: '&#156;', hex: '&#x9c;', title: 'Lowercase oe ligature'},
			'Ù': {shift: 'ZZZ', decimal: '&#217;', hex: '&#xd9;', title: 'Capital U-grave'},
			'ù': {shift: 'ZZZ', decimal: '&#249;', hex: '&#xf9;', title: 'Lowercase u-grave'},
			'Û': {shift: 'ZZZ', decimal: '&#219;', hex: '&#xdb;', title: 'Capital U-circumflex'},
			'û': {shift: 'ZZZ', decimal: '&#251;', hex: '&#xfb;', title: 'Lowercase U-circumflex'},
			'Ü': {shift: 'ZZZ', decimal: '&#220;', hex: '&#xdc;', title: 'Capital U-umlaut'},
			'ü': {shift: 'ZZZ', decimal: '&#252;', hex: '&#xfc;', title: 'Lowercase U-umlaut'},
			'«': {shift: 'ZZZ', decimal: '&#171;', hex: '&#xab;', title: 'Left angle quotes'},
			'»': {shift: 'ZZZ', decimal: '&#187;', hex: '&#xbb;', title: 'Right angle quotes'},
			'€': {shift: 'ZZZ', decimal: '&#128;', hex: '&#x80;', title: 'Eur'},
			'₣': {shift: 'ZZZ', decimal: '&#8355;', hex: '&#x20a3;', title: 'Fran'},

			'Á': {shift: 'ZZZ', decimal: '&#193;', hex: '&#xc1;', title: 'Capital A-acut'},
			'á': {shift: 'ZZZ', decimal: '&#225;', hex: '&#xe1;', title: 'Lowercase a-acut'},
			'Ą': {shift: 'ZZZ', decimal: '&#260;', hex: '&#x104;', title: 'Capital A-cedill'},
			'ą': {shift: 'ZZZ', decimal: '&#261;', hex: '&#x105;', title: 'Lowercase a-cedill'},
			'Ä': {shift: 'ZZZ', decimal: '&#196;', hex: '&#xc4;', title: 'Capital A-umlau'},
			'ä': {shift: 'ZZZ', decimal: '&#228;', hex: '&#xe4;', title: 'Lowercase a-umlau'},
			'É': {shift: 'ZZZ', decimal: '&#201;', hex: '&#xc9;', title: 'Capital E-acut'},
			'é': {shift: 'ZZZ', decimal: '&#233;', hex: '&#xe9;', title: 'Lowercase e-acut'},
			'Ę': {shift: 'ZZZ', decimal: '&#280;', hex: '&#x118;', title: 'Capital E-cedill'},
			'ę': {shift: 'ZZZ', decimal: '&#281;', hex: '&#x119;', title: 'Lowercase e-cedill'},
			'Ě': {shift: 'ZZZ', decimal: '&#282;', hex: '&#x11a;', title: 'Capital E-hache'},
			'ě': {shift: 'ZZZ', decimal: '&#283;', hex: '&#x11b;', title: 'Lowercase e-hache'},
			'Í': {shift: 'ZZZ', decimal: '&#205;', hex: '&#xcd;', title: 'Capital I-acut'},
			'í': {shift: 'ZZZ', decimal: '&#237;', hex: '&#xed;', title: 'Lowercase i-acut'},
			'Ó': {shift: 'ZZZ', decimal: '&#211;', hex: '&#xd3;', title: 'Capital O-acut'},
			'ó': {shift: 'ZZZ', decimal: '&#243;', hex: '&#xf3;', title: 'Lowercase o-acut'},
			'Ô': {shift: 'ZZZ', decimal: '&#212;', hex: '&#xd4;', title: 'Capital O-cir'},
			'ô': {shift: 'ZZZ', decimal: '&#244;', hex: '&#xf4;', title: 'Lowercase o-cir'},
			'Ú': {shift: 'ZZZ', decimal: '&#218;', hex: '&#xda;', title: 'Capital U-acut'},
			'ú': {shift: 'ZZZ', decimal: '&#250;', hex: '&#xfa;', title: 'Lowercase u-acut'},
			'Ů': {shift: 'ZZZ', decimal: '&#366;', hex: '&#x16e;', title: 'Capital U-rin'},
			'ů': {shift: 'ZZZ', decimal: '&#367;', hex: '&#x16f;', title: 'Lowercase u-rin'},
			'Ý': {shift: 'ZZZ', decimal: '&#221;', hex: '&#xdd;', title: 'Capital Y-acut'},
			'ý': {shift: 'ZZZ', decimal: '&#253;', hex: '&#xfd;', title: 'Lowercase y-acut'},
			'Č': {shift: 'ZZZ', decimal: '&#268;', hex: '&#x10c;', title: 'Capital C-hache'},
			'č': {shift: 'ZZZ', decimal: '&#269;', hex: '&#x10d;', title: 'Lowercase c-hache'},
			'ď': {shift: 'ZZZ', decimal: '&#271;', hex: '&#x10f;', title: 'd-apostroph'},
			'ť': {shift: 'ZZZ', decimal: '&#357;', hex: '&#x165;', title: 't-apostroph'},
			'Ĺ': {shift: 'ZZZ', decimal: '&#313;', hex: '&#x139;', title: 'Capital L-acut'},
			'ĺ': {shift: 'ZZZ', decimal: '&#314;', hex: '&#x13a;', title: 'Lowercase l-acut'},
			'Ň': {shift: 'ZZZ', decimal: '&#327;', hex: '&#x147;', title: 'Capital N-hache'},
			'ň': {shift: 'ZZZ', decimal: '&#328;', hex: '&#x148;', title: 'Lowercase n-hache'},
			'Ŕ': {shift: 'ZZZ', decimal: '&#340;', hex: '&#x154;', title: 'Capital R-acut'},
			'ŕ': {shift: 'ZZZ', decimal: '&#341;', hex: '&#x155;', title: 'Lowercase r-acut'},
			'Ř': {shift: 'ZZZ', decimal: '&#344;', hex: '&#x158;', title: 'Capital R-hache'},
			'ř': {shift: 'ZZZ', decimal: '&#345;', hex: '&#x159;', title: 'Lowercase r-hache'},
			'Š': {shift: 'ZZZ', decimal: '&#352;', hex: '&#x160;', title: 'Capital S-hache'},
			'š': {shift: 'ZZZ', decimal: '&#353;', hex: '&#x161;', title: 'Lowercase s-hache'},
			'Ž': {shift: 'ZZZ', decimal: '&#381;', hex: '&#x17d;', title: 'Capital Z-hache'},
			'ž': {shift: 'ZZZ', decimal: '&#382;', hex: '&#x17e;', title: 'Lowercase z-hache'},
			'Ä': {shift: 'ZZZ', decimal: '&#196;', hex: '&#xc4;', title: 'Capital A-umlaut'},
			'ä': {shift: 'ZZZ', decimal: '&#228;', hex: '&#xe4;', title: 'Lowercase a-umlaut'},
			'É': {shift: 'ZZZ', decimal: '&#201;', hex: '&#xc9;', title: 'Capital E-acute'},
			'é': {shift: 'ZZZ', decimal: '&#233;', hex: '&#xe9;', title: 'Lowercase E-acute'},
			'Ö': {shift: 'ZZZ', decimal: '&#214;', hex: '&#xd6;', title: 'Capital O-umlaut'},
			'ö': {shift: 'ZZZ', decimal: '&#246;', hex: '&#xf6;', title: 'Lowercase o-umlaut'},
			'Ü': {shift: 'ZZZ', decimal: '&#220;', hex: '&#xdc;', title: 'Capital U-umlaut'},
			'ü': {shift: 'ZZZ', decimal: '&#252;', hex: '&#xfc;', title: 'Lowercase u-umlaut'},
			'ß': {shift: 'ZZZ', decimal: '&#223;', hex: '&#xdf;', title: 'SZ ligature'},
			'«': {shift: 'ZZZ', decimal: '&#171;', hex: '&#xab;', title: 'Left angle quotes'},
			'»': {shift: 'ZZZ', decimal: '&#187;', hex: '&#xbb;', title: 'Right angle quotes'},
			'„': {shift: 'ZZZ', decimal: '&#132;', hex: '&#x84;', title: 'Left lower quotes'},
			'“': {shift: 'ZZZ', decimal: '&#147;', hex: '&#x93;', title: 'Left quotes'},
			'”': {shift: 'ZZZ', decimal: '&#148;', hex: '&#x94;', title: 'Right quotes'},
			'°': {shift: 'ZZZ', decimal: '&#176;', hex: '&#xb0;', title: 'Degree sign (Grad)'},
			'€': {shift: 'ZZZ', decimal: '&#128;', hex: '&#x80;', title: 'Eur'},
			'£': {shift: 'ZZZ', decimal: '&#163;', hex: '&#xa3;', title: 'Pound Sterling'},
			'À': {shift: 'ZZZ', decimal: '&#192;', hex: '&#xc0;', title: 'Capital A-grave'},
			'à': {shift: 'ZZZ', decimal: '&#224;', hex: '&#xe0;', title: 'Lowercase a-grave'},
			'Á': {shift: 'ZZZ', decimal: '&#193;', hex: '&#xc1;', title: 'Capital A-acute'},
			'á': {shift: 'ZZZ', decimal: '&#225;', hex: '&#xe1;', title: 'Lowercase A-acute'},
			'È': {shift: 'ZZZ', decimal: '&#200;', hex: '&#xc8;', title: 'Capital E-grave'},
			'è': {shift: 'ZZZ', decimal: '&#232;', hex: '&#xe8;', title: 'Lowercase e-grave'},
			'É': {shift: 'ZZZ', decimal: '&#201;', hex: '&#xc9;', title: 'Capital E-acute'},
			'é': {shift: 'ZZZ', decimal: '&#233;', hex: '&#xe9;', title: 'Lowercase e-acute'},
			'Ì': {shift: 'ZZZ', decimal: '&#204;', hex: '&#xcc;', title: 'Capital I-grave'},
			'ì': {shift: 'ZZZ', decimal: '&#236;', hex: '&#xec;', title: 'Lowercase i-grave'},
			'Í': {shift: 'ZZZ', decimal: '&#205;', hex: '&#xcd;', title: 'Capital I-acute'},
			'í': {shift: 'ZZZ', decimal: '&#237;', hex: '&#xed;', title: 'Lowercase I-acute'},
			'Ò': {shift: 'ZZZ', decimal: '&#210;', hex: '&#xd2;', title: 'Capital O-grave'},
			'ò': {shift: 'ZZZ', decimal: '&#242;', hex: '&#xf2;', title: 'Lowercase o-grave'},
			'Ó': {shift: 'ZZZ', decimal: '&#211;', hex: '&#xd3;', title: 'Capital O-acute'},
			'ó': {shift: 'ZZZ', decimal: '&#243;', hex: '&#xf3;', title: 'Lowercase o-acute'},
			'Ù': {shift: 'ZZZ', decimal: '&#217;', hex: '&#xd9;', title: 'Capital U-grave'},
			'ù': {shift: 'ZZZ', decimal: '&#249;', hex: '&#xf9;', title: 'Lowercase u-grave'},
			'Ú': {shift: 'ZZZ', decimal: '&#218;', hex: '&#xda;', title: 'Capital U-acute'},
			'ú': {shift: 'ZZZ', decimal: '&#250;', hex: '&#xfa;', title: 'Lowercase U-acute'},
			'«': {shift: 'ZZZ', decimal: '&#171;', hex: '&#xab;', title: 'Left angle quotes'},
			'»': {shift: 'ZZZ', decimal: '&#187;', hex: '&#xbb;', title: 'Right angle quotes'},
			'€': {shift: 'ZZZ', decimal: '&#128;', hex: '&#x80;', title: 'Eur'},
			'₤': {shift: 'ZZZ', decimal: '&#8356;', hex: '&#x20a4;', title: 'Lir'},
			'Ä': {shift: 'ZZZ', decimal: '&#196;', hex: '&#xc4;', title: 'Capital A-umlaut'},
			'ä': {shift: 'ZZZ', decimal: '&#228;', hex: '&#xe4;', title: 'Lowercase a-umlaut'},
			'É': {shift: 'ZZZ', decimal: '&#201;', hex: '&#xc9;', title: 'Capital E-acute'},
			'é': {shift: 'ZZZ', decimal: '&#233;', hex: '&#xe9;', title: 'Lowercase E-acute'},
			'Ö': {shift: 'ZZZ', decimal: '&#214;', hex: '&#xd6;', title: 'Capital O-umlaut'},
			'ö': {shift: 'ZZZ', decimal: '&#246;', hex: '&#xf6;', title: 'Lowercase o-umlaut'},
			'Ü': {shift: 'ZZZ', decimal: '&#220;', hex: '&#xdc;', title: 'Capital U-umlaut'},
			'ü': {shift: 'ZZZ', decimal: '&#252;', hex: '&#xfc;', title: 'Lowercase u-umlaut'},
			'ß': {shift: 'ZZZ', decimal: '&#223;', hex: '&#xdf;', title: 'SZ ligature'},
			'«': {shift: 'ZZZ', decimal: '&#171;', hex: '&#xab;', title: 'Left angle quotes'},
			'»': {shift: 'ZZZ', decimal: '&#187;', hex: '&#xbb;', title: 'Right angle quotes'},
			'„': {shift: 'ZZZ', decimal: '&#132;', hex: '&#x84;', title: 'Left lower quotes'},
			'“': {shift: 'ZZZ', decimal: '&#147;', hex: '&#x93;', title: 'Left quotes'},
			'”': {shift: 'ZZZ', decimal: '&#148;', hex: '&#x94;', title: 'Right quotes'},
			'°': {shift: 'ZZZ', decimal: '&#176;', hex: '&#xb0;', title: 'Degree sign (Grad)'},
			'€': {shift: 'ZZZ', decimal: '&#128;', hex: '&#x80;', title: 'Eur'},
			'£': {shift: 'ZZZ', decimal: '&#163;', hex: '&#xa3;', title: 'Pound Sterling'}
		};


		this.all2 = {
			  '0': '{shift: 'ZZZ', decimal: '48;', hex: '30', title: 'zero', html:'&#48;', htmlName: ''}',
			  '1': '{shift: 'ZZZ', decimal: '49;', hex: '31', title: 'one', html:'&#49;', htmlName: ''}',
			  '2': '{shift: 'ZZZ', decimal: '50;', hex: '32', title: 'two', html:'&#50;', htmlName: ''}',
			  '3': '{shift: 'ZZZ', decimal: '51;', hex: '33', title: 'three', html:'&#51;', htmlName: ''}',
			  '4': '{shift: 'ZZZ', decimal: '52;', hex: '34', title: 'four', html:'&#52;', htmlName: ''}',
			  '5': '{shift: 'ZZZ', decimal: '53;', hex: '35', title: 'five', html:'&#53;', htmlName: ''}',
			  '6': '{shift: 'ZZZ', decimal: '54;', hex: '36', title: 'six', html:'&#54;', htmlName: ''}',
			  '7': '{shift: 'ZZZ', decimal: '55;', hex: '37', title: 'seven', html:'&#55;', htmlName: ''}',
			  '8': '{shift: 'ZZZ', decimal: '56;', hex: '38', title: 'eight', html:'&#56;', htmlName: ''}',
			  '9': '{shift: 'ZZZ', decimal: '57;', hex: '39', title: 'nine', html:'&#57;', htmlName: ''}',
			  ' ': '{shift: 'ZZZ', decimal: '32;', hex: '20', title: 'space', html:'&#32;', htmlName: ''}',
			  '!': '{shift: 'ZZZ', decimal: '33;', hex: '21', title: 'exclamation point', html:'&#33;', htmlName: ''}',
			  '"': '{shift: 'ZZZ', decimal: '34;', hex: '22', title: 'double quotes', html:'&#34;', htmlName: '&quot;'}',
			  '#': '{shift: 'ZZZ', decimal: '35;', hex: '23', title: 'number sign', html:'&#35;', htmlName: ''}',
			  '$': '{shift: 'ZZZ', decimal: '36;', hex: '24', title: 'dollar sign', html:'&#36;', htmlName: ''}',
			  '%': '{shift: 'ZZZ', decimal: '37;', hex: '25', title: 'percent sign', html:'&#37;', htmlName: ''}',
			  '&': '{shift: 'ZZZ', decimal: '38;', hex: '26', title: 'ampersand', html:'&#38;', htmlName: '&amp;'}',
			  '\'': '{shift: 'ZZZ', decimal: '39;', hex: '27', title: 'single quote', html:'&#39;', htmlName: ''}',
			  '(': '{shift: 'ZZZ', decimal: '40;', hex: '28', title: 'opening parenthesis', html:'&#40;', htmlName: ''}',
			  ')': '{shift: 'ZZZ', decimal: '41;', hex: '29', title: 'closing parenthesis', html:'&#41;', htmlName: ''}',
			  '*': '{shift: 'ZZZ', decimal: '42;', hex: '2A', title: 'asterisk', html:'&#42;', htmlName: ''}',
			  '+': '{shift: 'ZZZ', decimal: '43;', hex: '2B', title: 'plus sign', html:'&#43;', htmlName: ''}',
			  ',': '{shift: 'ZZZ', decimal: '44;', hex: '2C', title: 'comma', html:'&#44;', htmlName: ''}',
			  '-': '{shift: 'ZZZ', decimal: '45;', hex: '2D', title: 'minus sign - hyphen', html:'&#45;', htmlName: ''}',
			  '.': '{shift: 'ZZZ', decimal: '46;', hex: '2E', title: 'period', html:'&#46;', htmlName: ''}',
			  '/': '{shift: 'ZZZ', decimal: '47;', hex: '2F', title: 'slash', html:'&#47;', htmlName: ''}',
			  ':': '{shift: 'ZZZ', decimal: '58;', hex: '3A', title: 'colon', html:'&#58;', htmlName: ''}',
			  ';': '{shift: 'ZZZ', decimal: '59;', hex: '3B', title: 'semicolon', html:'&#59;', htmlName: ''}',
			  '&lt;': '{shift: 'ZZZ', decimal: '60;', hex: '3C', title: 'less than sign', html:'&#60;', htmlName: '&lt;'}',
			  '=': '{shift: 'ZZZ', decimal: '61;', hex: '3D', title: 'equal sign', html:'&#61;', htmlName: ''}',
			  '&gt;': '{shift: 'ZZZ', decimal: '62;', hex: '3E', title: 'greater than sign', html:'&#62;', htmlName: '&gt;'}',
			  '?': '{shift: 'ZZZ', decimal: '63;', hex: '3F', title: 'question mark', html:'&#63;', htmlName: ''}',
			  '@': '{shift: 'ZZZ', decimal: '64;', hex: '40', title: 'at symbol', html:'&#64;', htmlName: ''}',
			  A: '{shift: 'ZZZ', decimal: '65;', hex: '41', title: '', html:'&#65;', htmlName: ''}',
			  B: '{shift: 'ZZZ', decimal: '66;', hex: '42', title: '', html:'&#66;', htmlName: ''}',
			  C: '{shift: 'ZZZ', decimal: '67;', hex: '43', title: '', html:'&#67;', htmlName: ''}',
			  D: '{shift: 'ZZZ', decimal: '68;', hex: '44', title: '', html:'&#68;', htmlName: ''}',
			  E: '{shift: 'ZZZ', decimal: '69;', hex: '45', title: '', html:'&#69;', htmlName: ''}',
			  F: '{shift: 'ZZZ', decimal: '70;', hex: '46', title: '', html:'&#70;', htmlName: ''}',
			  G: '{shift: 'ZZZ', decimal: '71;', hex: '47', title: '', html:'&#71;', htmlName: ''}',
			  H: '{shift: 'ZZZ', decimal: '72;', hex: '48', title: '', html:'&#72;', htmlName: ''}',
			  I: '{shift: 'ZZZ', decimal: '73;', hex: '49', title: '', html:'&#73;', htmlName: ''}',
			  J: '{shift: 'ZZZ', decimal: '74;', hex: '4A', title: '', html:'&#74;', htmlName: ''}',
			  K: '{shift: 'ZZZ', decimal: '75;', hex: '4B', title: '', html:'&#75;', htmlName: ''}',
			  L: '{shift: 'ZZZ', decimal: '76;', hex: '4C', title: '', html:'&#76;', htmlName: ''}',
			  M: '{shift: 'ZZZ', decimal: '77;', hex: '4D', title: '', html:'&#77;', htmlName: ''}',
			  N: '{shift: 'ZZZ', decimal: '78;', hex: '4E', title: '', html:'&#78;', htmlName: ''}',
			  O: '{shift: 'ZZZ', decimal: '79;', hex: '4F', title: '', html:'&#79;', htmlName: ''}',
			  P: '{shift: 'ZZZ', decimal: '80;', hex: '50', title: '', html:'&#80;', htmlName: ''}',
			  Q: '{shift: 'ZZZ', decimal: '81;', hex: '51', title: '', html:'&#81;', htmlName: ''}',
			  R: '{shift: 'ZZZ', decimal: '82;', hex: '52', title: '', html:'&#82;', htmlName: ''}',
			  S: '{shift: 'ZZZ', decimal: '83;', hex: '53', title: '', html:'&#83;', htmlName: ''}',
			  T: '{shift: 'ZZZ', decimal: '84;', hex: '54', title: '', html:'&#84;', htmlName: ''}',
			  U: '{shift: 'ZZZ', decimal: '85;', hex: '55', title: '', html:'&#85;', htmlName: ''}',
			  V: '{shift: 'ZZZ', decimal: '86;', hex: '56', title: '', html:'&#86;', htmlName: ''}',
			  W: '{shift: 'ZZZ', decimal: '87;', hex: '57', title: '', html:'&#87;', htmlName: ''}',
			  X: '{shift: 'ZZZ', decimal: '88;', hex: '58', title: '', html:'&#88;', htmlName: ''}',
			  Y: '{shift: 'ZZZ', decimal: '89;', hex: '59', title: '', html:'&#89;', htmlName: ''}',
			  Z: '{shift: 'ZZZ', decimal: '90;', hex: '5A', title: '', html:'&#90;', htmlName: ''}',
			  '[': '{shift: 'ZZZ', decimal: '91;', hex: '5B', title: 'opening bracket', html:'&#91;', htmlName: ''}',
			  '': '{shift: 'ZZZ', decimal: '92;', hex: '5C', title: 'backslash', html:'&#92;', htmlName: ''}',
			  ']': '{shift: 'ZZZ', decimal: '93;', hex: '5D', title: 'closing bracket', html:'&#93;', htmlName: ''}',
			  '^': '{shift: 'ZZZ', decimal: '94;', hex: '5E', title: 'caret - circumflex', html:'&#94;', htmlName: ''}',
			  _: '{shift: 'ZZZ', decimal: '95;', hex: '5F', title: 'underscore', html:'&#95;', htmlName: ''}',
			  '`': '{shift: 'ZZZ', decimal: '96;', hex: '60', title: 'grave accent', html:'&#96;', htmlName: ''}',
			  a: '{shift: 'ZZZ', decimal: '97;', hex: '61', title: '', html:'&#97;', htmlName: ''}',
			  b: '{shift: 'ZZZ', decimal: '98;', hex: '62', title: '', html:'&#98;', htmlName: ''}',
			  c: '{shift: 'ZZZ', decimal: '99;', hex: '63', title: '', html:'&#99;', htmlName: ''}',
			  d: '{shift: 'ZZZ', decimal: '100;', hex: '64', title: '', html:'&#100;', htmlName: ''}',
			  e: '{shift: 'ZZZ', decimal: '101;', hex: '65', title: '', html:'&#101;', htmlName: ''}',
			  f: '{shift: 'ZZZ', decimal: '102;', hex: '66', title: '', html:'&#102;', htmlName: ''}',
			  g: '{shift: 'ZZZ', decimal: '103;', hex: '67', title: '', html:'&#103;', htmlName: ''}',
			  h: '{shift: 'ZZZ', decimal: '104;', hex: '68', title: '', html:'&#104;', htmlName: ''}',
			  i: '{shift: 'ZZZ', decimal: '105;', hex: '69', title: '', html:'&#105;', htmlName: ''}',
			  j: '{shift: 'ZZZ', decimal: '106;', hex: '6A', title: '', html:'&#106;', htmlName: ''}',
			  k: '{shift: 'ZZZ', decimal: '107;', hex: '6B', title: '', html:'&#107;', htmlName: ''}',
			  l: '{shift: 'ZZZ', decimal: '108;', hex: '6C', title: '', html:'&#108;', htmlName: ''}',
			  m: '{shift: 'ZZZ', decimal: '109;', hex: '6D', title: '', html:'&#109;', htmlName: ''}',
			  n: '{shift: 'ZZZ', decimal: '110;', hex: '6E', title: '', html:'&#110;', htmlName: ''}',
			  o: '{shift: 'ZZZ', decimal: '111;', hex: '6F', title: '', html:'&#111;', htmlName: ''}',
			  p: '{shift: 'ZZZ', decimal: '112;', hex: '70', title: '', html:'&#112;', htmlName: ''}',
			  q: '{shift: 'ZZZ', decimal: '113;', hex: '71', title: '', html:'&#113;', htmlName: ''}',
			  r: '{shift: 'ZZZ', decimal: '114;', hex: '72', title: '', html:'&#114;', htmlName: ''}',
			  s: '{shift: 'ZZZ', decimal: '115;', hex: '73', title: '', html:'&#115;', htmlName: ''}',
			  t: '{shift: 'ZZZ', decimal: '116;', hex: '74', title: '', html:'&#116;', htmlName: ''}',
			  u: '{shift: 'ZZZ', decimal: '117;', hex: '75', title: '', html:'&#117;', htmlName: ''}',
			  v: '{shift: 'ZZZ', decimal: '118;', hex: '76', title: '', html:'&#118;', htmlName: ''}',
			  w: '{shift: 'ZZZ', decimal: '119;', hex: '77', title: '', html:'&#119;', htmlName: ''}',
			  x: '{shift: 'ZZZ', decimal: '120;', hex: '78', title: '', html:'&#120;', htmlName: ''}',
			  y: '{shift: 'ZZZ', decimal: '121;', hex: '79', title: '', html:'&#121;', htmlName: ''}',
			  z: '{shift: 'ZZZ', decimal: '122;', hex: '7A', title: '', html:'&#122;', htmlName: ''}',
			  '{': '{shift: 'ZZZ', decimal: '123;', hex: '7B', title: 'opening brace', html:'&#123;', htmlName: ''}',
			  '|': '{shift: 'ZZZ', decimal: '124;', hex: '7C', title: 'vertical bar', html:'&#124;', htmlName: ''}',
			  '}': '{shift: 'ZZZ', decimal: '125;', hex: '7D', title: 'closing brace', html:'&#125;', htmlName: ''}',
			  '~': '{shift: 'ZZZ', decimal: '126;', hex: '7E', title: 'equivalency sign - tilde', html:'&#126;', htmlName: ''}',
			  '&nbsp;': '{shift: 'ZZZ', decimal: '160;', hex: 'A0', title: 'non-breaking space', html:'&#160;', htmlName: '&nbsp;'}',
			  '¡': '{shift: 'ZZZ', decimal: '161;', hex: 'A1', title: 'inverted exclamation mark', html:'&#161;', htmlName: '&iexcl;'}',
			  '¢': '{shift: 'ZZZ', decimal: '162;', hex: 'A2', title: 'cent sign', html:'&#162;', htmlName: '&cent;'}',
			  '£': '{shift: 'ZZZ', decimal: '163;', hex: 'A3', title: 'pound sign', html:'&#163;', htmlName: '&pound;'}',
			  '¤': '{shift: 'ZZZ', decimal: '164;', hex: 'A4', title: 'currency sign', html:'&#164;', htmlName: '&curren;'}',
			  '¥': '{shift: 'ZZZ', decimal: '165;', hex: 'A5', title: 'yen sign', html:'&#165;', htmlName: '&yen;'}',
			  '¦': '{shift: 'ZZZ', decimal: '166;', hex: 'A6', title: 'broken vertical bar', html:'&#166;', htmlName: '&brvbar;'}',
			  '§': '{shift: 'ZZZ', decimal: '167;', hex: 'A7', title: 'section sign', html:'&#167;', htmlName: '&sect;'}',
			  '¨': '{shift: 'ZZZ', decimal: '168;', hex: 'A8', title: 'spacing diaeresis - umlaut', html:'&#168;', htmlName: '&uml;'}',
			  '©': '{shift: 'ZZZ', decimal: '169;', hex: 'A9', title: 'copyright sign', html:'&#169;', htmlName: '&copy;'}',
			  'ª': '{shift: 'ZZZ', decimal: '170;', hex: 'AA', title: 'feminine ordinal indicator', html:'&#170;', htmlName: '&ordf;'}',
			  '«': '{shift: 'ZZZ', decimal: '171;', hex: 'AB', title: 'left double angle quotes', html:'&#171;', htmlName: '&laquo;'}',
			  '¬': '{shift: 'ZZZ', decimal: '172;', hex: 'AC', title: 'not sign', html:'&#172;', htmlName: '&not;'}',
			  '­': '{shift: 'ZZZ', decimal: '173;', hex: 'AD', title: 'soft hyphen', html:'&#173;', htmlName: '&shy;'}',
			  '®': '{shift: 'ZZZ', decimal: '174;', hex: 'AE', title: 'registered trade mark sign', html:'&#174;', htmlName: '&reg;'}',
			  '¯': '{shift: 'ZZZ', decimal: '175;', hex: 'AF', title: 'spacing macron - overline', html:'&#175;', htmlName: '&macr;'}',
			  '°': '{shift: 'ZZZ', decimal: '176;', hex: 'B0', title: 'degree sign', html:'&#176;', htmlName: '&deg;'}',
			  '±': '{shift: 'ZZZ', decimal: '177;', hex: 'B1', title: 'plus-or-minus sign', html:'&#177;', htmlName: '&plusmn;'}',
			  '²': '{shift: 'ZZZ', decimal: '178;', hex: 'B2', title: 'superscript two - squared', html:'&#178;', htmlName: '&sup2;'}',
			  '³': '{shift: 'ZZZ', decimal: '179;', hex: 'B3', title: 'superscript three - cubed', html:'&#179;', htmlName: '&sup3;'}',
			  '´': '{shift: 'ZZZ', decimal: '180;', hex: 'B4', title: 'acute accent - spacing acute', html:'&#180;', htmlName: '&acute;'}',
			  'µ': '{shift: 'ZZZ', decimal: '181;', hex: 'B5', title: 'micro sign', html:'&#181;', htmlName: '&micro;'}',
			  '¶': '{shift: 'ZZZ', decimal: '182;', hex: 'B6', title: 'pilcrow sign - paragraph sign', html:'&#182;', htmlName: '&para;'}',
			  '·': '{shift: 'ZZZ', decimal: '183;', hex: 'B7', title: 'middle dot - Georgian comma', html:'&#183;', htmlName: '&middot;'}',
			  '¸': '{shift: 'ZZZ', decimal: '184;', hex: 'B8', title: 'spacing cedilla', html:'&#184;', htmlName: '&cedil;'}',
			  '¹': '{shift: 'ZZZ', decimal: '185;', hex: 'B9', title: 'superscript one', html:'&#185;', htmlName: '&sup1;'}',
			  'º': '{shift: 'ZZZ', decimal: '186;', hex: 'BA', title: 'masculine ordinal indicator', html:'&#186;', htmlName: '&ordm;'}',
			  '»': '{shift: 'ZZZ', decimal: '187;', hex: 'BB', title: 'right double angle quotes', html:'&#187;', htmlName: '&raquo;'}',
			  '¼': '{shift: 'ZZZ', decimal: '188;', hex: 'BC', title: 'fraction one quarter', html:'&#188;', htmlName: '&frac14;'}',
			  '½': '{shift: 'ZZZ', decimal: '189;', hex: 'BD', title: 'fraction one half', html:'&#189;', htmlName: '&frac12;'}',
			  '¾': '{shift: 'ZZZ', decimal: '190;', hex: 'BE', title: 'fraction three quarters', html:'&#190;', htmlName: '&frac34;'}',
			  '¿': '{shift: 'ZZZ', decimal: '191;', hex: 'BF', title: 'inverted question mark', html:'&#191;', htmlName: '&iquest;'}',
			  'À': '{shift: 'ZZZ', decimal: '192;', hex: 'C0', title: 'latin capital letter A with grave', html:'&#192;', htmlName: '&Agrave;'}',
			  'Á': '{shift: 'ZZZ', decimal: '193;', hex: 'C1', title: 'latin capital letter A with acute', html:'&#193;', htmlName: '&Aacute;'}',
			  'Â': '{shift: 'ZZZ', decimal: '194;', hex: 'C2', title: 'latin capital letter A with circumflex', html:'&#194;', htmlName: '&Acirc;'}',
			  'Ã': '{shift: 'ZZZ', decimal: '195;', hex: 'C3', title: 'latin capital letter A with tilde', html:'&#195;', htmlName: '&Atilde;'}',
			  'Ä': '{shift: 'ZZZ', decimal: '196;', hex: 'C4', title: 'latin capital letter A with diaeresis', html:'&#196;', htmlName: '&Auml;'}',
			  'Å': '{shift: 'ZZZ', decimal: '197;', hex: 'C5', title: 'latin capital letter A with ring above', html:'&#197;', htmlName: '&Aring;'}',
			  'Æ': '{shift: 'ZZZ', decimal: '198;', hex: 'C6', title: 'latin capital letter AE', html:'&#198;', htmlName: '&AElig;'}',
			  'Ç': '{shift: 'ZZZ', decimal: '199;', hex: 'C7', title: 'latin capital letter C with cedilla', html:'&#199;', htmlName: '&Ccedil;'}',
			  'È': '{shift: 'ZZZ', decimal: '200;', hex: 'C8', title: 'latin capital letter E with grave', html:'&#200;', htmlName: '&Egrave;'}',
			  'É': '{shift: 'ZZZ', decimal: '201;', hex: 'C9', title: 'latin capital letter E with acute', html:'&#201;', htmlName: '&Eacute;'}',
			  'Ê': '{shift: 'ZZZ', decimal: '202;', hex: 'CA', title: 'latin capital letter E with circumflex', html:'&#202;', htmlName: '&Ecirc;'}',
			  'Ë': '{shift: 'ZZZ', decimal: '203;', hex: 'CB', title: 'latin capital letter E with diaeresis', html:'&#203;', htmlName: '&Euml;'}',
			  'Ì': '{shift: 'ZZZ', decimal: '204;', hex: 'CC', title: 'latin capital letter I with grave', html:'&#204;', htmlName: '&Igrave;'}',
			  'Í': '{shift: 'ZZZ', decimal: '205;', hex: 'CD', title: 'latin capital letter I with acute', html:'&#205;', htmlName: '&Iacute;'}',
			  'Î': '{shift: 'ZZZ', decimal: '206;', hex: 'CE', title: 'latin capital letter I with circumflex', html:'&#206;', htmlName: '&Icirc;'}',
			  'Ï': '{shift: 'ZZZ', decimal: '207;', hex: 'CF', title: 'latin capital letter I with diaeresis', html:'&#207;', htmlName: '&Iuml;'}',
			  'Ð': '{shift: 'ZZZ', decimal: '208;', hex: 'D0', title: 'latin capital letter ETH', html:'&#208;', htmlName: '&ETH;'}',
			  'Ñ': '{shift: 'ZZZ', decimal: '209;', hex: 'D1', title: 'latin capital letter N with tilde', html:'&#209;', htmlName: '&Ntilde;'}',
			  'Ò': '{shift: 'ZZZ', decimal: '210;', hex: 'D2', title: 'latin capital letter O with grave', html:'&#210;', htmlName: '&Ograve;'}',
			  'Ó': '{shift: 'ZZZ', decimal: '211;', hex: 'D3', title: 'latin capital letter O with acute', html:'&#211;', htmlName: '&Oacute;'}',
			  'Ô': '{shift: 'ZZZ', decimal: '212;', hex: 'D4', title: 'latin capital letter O with circumflex', html:'&#212;', htmlName: '&Ocirc;'}',
			  'Õ': '{shift: 'ZZZ', decimal: '213;', hex: 'D5', title: 'latin capital letter O with tilde', html:'&#213;', htmlName: '&Otilde;'}',
			  'Ö': '{shift: 'ZZZ', decimal: '214;', hex: 'D6', title: 'latin capital letter O with diaeresis', html:'&#214;', htmlName: '&Ouml;'}',
			  '×': '{shift: 'ZZZ', decimal: '215;', hex: 'D7', title: 'multiplication sign', html:'&#215;', htmlName: '&times;'}',
			  'Ø': '{shift: 'ZZZ', decimal: '216;', hex: 'D8', title: 'latin capital letter O with slash', html:'&#216;', htmlName: '&Oslash;'}',
			  'Ù': '{shift: 'ZZZ', decimal: '217;', hex: 'D9', title: 'latin capital letter U with grave', html:'&#217;', htmlName: '&Ugrave;'}',
			  'Ú': '{shift: 'ZZZ', decimal: '218;', hex: 'DA', title: 'latin capital letter U with acute', html:'&#218;', htmlName: '&Uacute;'}',
			  'Û': '{shift: 'ZZZ', decimal: '219;', hex: 'DB', title: 'latin capital letter U with circumflex', html:'&#219;', htmlName: '&Ucirc;'}',
			  'Ü': '{shift: 'ZZZ', decimal: '220;', hex: 'DC', title: 'latin capital letter U with diaeresis', html:'&#220;', htmlName: '&Uuml;'}',
			  'Ý': '{shift: 'ZZZ', decimal: '221;', hex: 'DD', title: 'latin capital letter Y with acute', html:'&#221;', htmlName: '&Yacute;'}',
			  'Þ': '{shift: 'ZZZ', decimal: '222;', hex: 'DE', title: 'latin capital letter THORN', html:'&#222;', htmlName: '&THORN;'}',
			  'ß': '{shift: 'ZZZ', decimal: '223;', hex: 'DF', title: 'latin small letter sharp s - ess-zed', html:'&#223;', htmlName: '&szlig;'}',
			  'à': '{shift: 'ZZZ', decimal: '224;', hex: 'E0', title: 'latin small letter a with grave', html:'&#224;', htmlName: '&agrave;'}',
			  'á': '{shift: 'ZZZ', decimal: '225;', hex: 'E1', title: 'latin small letter a with acute', html:'&#225;', htmlName: '&aacute;'}',
			  'â': '{shift: 'ZZZ', decimal: '226;', hex: 'E2', title: 'latin small letter a with circumflex', html:'&#226;', htmlName: '&acirc;'}',
			  'ã': '{shift: 'ZZZ', decimal: '227;', hex: 'E3', title: 'latin small letter a with tilde', html:'&#227;', htmlName: '&atilde;'}',
			  'ä': '{shift: 'ZZZ', decimal: '228;', hex: 'E4', title: 'latin small letter a with diaeresis', html:'&#228;', htmlName: '&auml;'}',
			  'å': '{shift: 'ZZZ', decimal: '229;', hex: 'E5', title: 'latin small letter a with ring above', html:'&#229;', htmlName: '&aring;'}',
			  'æ': '{shift: 'ZZZ', decimal: '230;', hex: 'E6', title: 'latin small letter ae', html:'&#230;', htmlName: '&aelig;'}',
			  'ç': '{shift: 'ZZZ', decimal: '231;', hex: 'E7', title: 'latin small letter c with cedilla', html:'&#231;', htmlName: '&ccedil;'}',
			  'è': '{shift: 'ZZZ', decimal: '232;', hex: 'E8', title: 'latin small letter e with grave', html:'&#232;', htmlName: '&egrave;'}',
			  'é': '{shift: 'ZZZ', decimal: '233;', hex: 'E9', title: 'latin small letter e with acute', html:'&#233;', htmlName: '&eacute;'}',
			  'ê': '{shift: 'ZZZ', decimal: '234;', hex: 'EA', title: 'latin small letter e with circumflex', html:'&#234;', htmlName: '&ecirc;'}',
			  'ë': '{shift: 'ZZZ', decimal: '235;', hex: 'EB', title: 'latin small letter e with diaeresis', html:'&#235;', htmlName: '&euml;'}',
			  'ì': '{shift: 'ZZZ', decimal: '236;', hex: 'EC', title: 'latin small letter i with grave', html:'&#236;', htmlName: '&igrave;'}',
			  'í': '{shift: 'ZZZ', decimal: '237;', hex: 'ED', title: 'latin small letter i with acute', html:'&#237;', htmlName: '&iacute;'}',
			  'î': '{shift: 'ZZZ', decimal: '238;', hex: 'EE', title: 'latin small letter i with circumflex', html:'&#238;', htmlName: '&icirc;'}',
			  'ï': '{shift: 'ZZZ', decimal: '239;', hex: 'EF', title: 'latin small letter i with diaeresis', html:'&#239;', htmlName: '&iuml;'}',
			  'ð': '{shift: 'ZZZ', decimal: '240;', hex: 'F0', title: 'latin small letter eth', html:'&#240;', htmlName: '&eth;'}',
			  'ñ': '{shift: 'ZZZ', decimal: '241;', hex: 'F1', title: 'latin small letter n with tilde', html:'&#241;', htmlName: '&ntilde;'}',
			  'ò': '{shift: 'ZZZ', decimal: '242;', hex: 'F2', title: 'latin small letter o with grave', html:'&#242;', htmlName: '&ograve;'}',
			  'ó': '{shift: 'ZZZ', decimal: '243;', hex: 'F3', title: 'latin small letter o with acute', html:'&#243;', htmlName: '&oacute;'}',
			  'ô': '{shift: 'ZZZ', decimal: '244;', hex: 'F4', title: 'latin small letter o with circumflex', html:'&#244;', htmlName: '&ocirc;'}',
			  'õ': '{shift: 'ZZZ', decimal: '245;', hex: 'F5', title: 'latin small letter o with tilde', html:'&#245;', htmlName: '&otilde;'}',
			  'ö': '{shift: 'ZZZ', decimal: '246;', hex: 'F6', title: 'latin small letter o with diaeresis', html:'&#246;', htmlName: '&ouml;'}',
			  '÷': '{shift: 'ZZZ', decimal: '247;', hex: 'F7', title: 'division sign', html:'&#247;', htmlName: '&divide;'}',
			  'ø': '{shift: 'ZZZ', decimal: '248;', hex: 'F8', title: 'latin small letter o with slash', html:'&#248;', htmlName: '&oslash;'}',
			  'ù': '{shift: 'ZZZ', decimal: '249;', hex: 'F9', title: 'latin small letter u with grave', html:'&#249;', htmlName: '&ugrave;'}',
			  'ú': '{shift: 'ZZZ', decimal: '250;', hex: 'FA', title: 'latin small letter u with acute', html:'&#250;', htmlName: '&uacute;'}',
			  'û': '{shift: 'ZZZ', decimal: '251;', hex: 'FB', title: 'latin small letter u with circumflex', html:'&#251;', htmlName: '&ucirc;'}',
			  'ü': '{shift: 'ZZZ', decimal: '252;', hex: 'FC', title: 'latin small letter u with diaeresis', html:'&#252;', htmlName: '&uuml;'}',
			  'ý': '{shift: 'ZZZ', decimal: '253;', hex: 'FD', title: 'latin small letter y with acute', html:'&#253;', htmlName: '&yacute;'}',
			  'þ': '{shift: 'ZZZ', decimal: '254;', hex: 'FE', title: 'latin small letter thorn', html:'&#254;', htmlName: '&thorn;'}',
			  'ÿ': '{shift: 'ZZZ', decimal: '255;', hex: 'FF', title: 'latin small letter y with diaeresis', html:'&#255;', htmlName: '&yuml;'}',
			  'Œ': '{shift: 'ZZZ', decimal: '338;', hex: '152', title: 'latin capital letter OE', html:'&#338;', htmlName: ''}',
			  'œ': '{shift: 'ZZZ', decimal: '339;', hex: '153', title: 'latin small letter oe', html:'&#339;', htmlName: ''}',
			  'Š': '{shift: 'ZZZ', decimal: '352;', hex: '160', title: 'latin capital letter S with caron', html:'&#352;', htmlName: ''}',
			  'š': '{shift: 'ZZZ', decimal: '353;', hex: '161', title: 'latin small letter s with caron', html:'&#353;', htmlName: ''}',
			  'Ÿ': '{shift: 'ZZZ', decimal: '376;', hex: '178', title: 'latin capital letter Y with diaeresis', html:'&#376;', htmlName: ''}',
			  'ƒ': '{shift: 'ZZZ', decimal: '402;', hex: '192', title: 'latin small f with hook - function', html:'&#402;', htmlName: ''}'
}

module.exports = LetterSet;
