'use strict';
// https://en.wikipedia.org/wiki/Western_Latin_character_sets_(computing)
// http://character-code.com/czech_slovak_slovenian-html-codes.php
// http://www.ascii.cl/htmlcodes.htm
// http://www.ascii-code.com/

function LetterSet() {

		this.lowerSet = {
			'á': {shift:'Á', html:'&#_ZZ_;', hex:null, name:'aacute', info:'small a, acute accent' },
			'â': {shift:'Â', html:'&#_ZZ_;', hex:null, name:'acirc', info:'small a, circumflex accent' },
			'à': {shift:'À', html:'&#_ZZ_;', hex:null, name:'agrave', info:'small a, grave accent' },
			'å': {shift:'Å', html:'&#_ZZ_;', hex:null, name:'aring', info:'small a, ring' },
			'ã': {shift:'Ã', html:'&#_ZZ_;', hex:null, name:'atilde', info:'small a, tilde' },
			'ä': {shift:'Ä', html:'&#_ZZ_;', hex:null, name:'auml', info:'small a, dieresis or umlautmark' },
			'æ': {shift:'Æ', html:'&#_ZZ_;', hex:null, name:'aelig', info:'small ae diphthong (ligature)' },
			'ç': {shift:'Ç', html:'&#_ZZ_;', hex:null, name:'ccedil', info:'small c, cedilla' },
			'ð': {shift:'Ð', html:'&#_ZZ_;', hex:null, name:'eth', info:'small eth, Icelandic' },
			'é': {shift:'É', html:'&#_ZZ_;', hex:null, name:'eacute', info:'small e, acute accent' },
			'ê': {shift:'Ê', html:'&#_ZZ_;', hex:null, name:'ecirc', info:'small e, circumflex accent' },
			'è': {shift:'È', html:'&#_ZZ_;', hex:null, name:'egrave', info:'small e, grave accent' },
			'ë': {shift:'Ë', html:'&#_ZZ_;', hex:null, name:'euml', info:'small e, dieresis or umlautmark' },
			'í': {shift:'Í', html:'&#_ZZ_;', hex:null, name:'iacute', info:'small i, acute accent' },
			'î': {shift:'Î', html:'&#_ZZ_;', hex:null, name:'icirc', info:'small i, circumflex accent' },
			'ì': {shift:'Ì', html:'&#_ZZ_;', hex:null, name:'igrave', info:'small i, grave accent' },
			'ï': {shift:'Ï', html:'&#_ZZ_;', hex:null, name:'iuml', info:'small i, dieresis or umlautmark' },
			'ñ': {shift:'Ñ', html:'&#_ZZ_;', hex:null, name:'ntilde', info:'small n, tilde' },
			'ó': {shift:'Ó', html:'&#_ZZ_;', hex:null, name:'oacute', info:'small o, acute accent' },
			'ô': {shift:'Ô', html:'&#_ZZ_;', hex:null, name:'ocirc', info:'small o, circumflex accent' },
			'ò': {shift:'Ò', html:'&#_ZZ_;', hex:null, name:'ograve', info:'small o, grave accent' },
			'ø': {shift:'Ø', html:'&#_ZZ_;', hex:null, name:'oslash', info:'small o, slash' },
			'õ': {shift:'Õ', html:'&#_ZZ_;', hex:null, name:'otilde', info:'small o, tilde' },
			'ö': {shift:'Ö', html:'&#_ZZ_;', hex:null, name:'ouml', info:'small o, dieresis or umlautmark' },
			'ß': {shift:'SS',html:'&#_ZZ_;', hex:null, name:'szlig', info:'small sharp s, German (szligature)' },
			'þ': {shift:'Þ', html:'&#_ZZ_;', hex:null, name:'thorn', info:'small thorn, Icelandic' },
			'Þ': {shift:'þ', html:'&#_ZZ_;', hex:null, name:'THORN', info:'capital THORN, Icelandic' },
			'ú': {shift:'Ú', html:'&#_ZZ_;', hex:null, name:'uacute', info:'small u, acute accent' },
			'û': {shift:'Û', html:'&#_ZZ_;', hex:null, name:'ucirc', info:'small u, circumflex accent' },
			'ù': {shift:'Ù', html:'&#_ZZ_;', hex:null, name:'ugrave', info:'small u, grave accent' },
			'ü': {shift:'Ü', html:'&#_ZZ_;', hex:null, name:'uuml', info:'small u, dieresis or umlautmark' },
			'ý': {shift:'Ý', html:'&#_ZZ_;', hex:null, name:'yacute', info:'small y, acute accent' },
			'ÿ': {shift:'',  html:'&#_ZZ_;', hex:null, name:'yuml', info:'small y, dieresis or umlautmark' },
			'a': {shift:'A', html:'&#97;', hex:0x61 },
			'b': {shift:'B', html:'&#98;', hex:0x62 },
			'c': {shift:'C', html:'&#99;', hex:0x63 },
			'd': {shift:'D', html:'&#100;', hex:0x64 },
			'e': {shift:'E', html:'&#101;', hex:0x65 },
			'f': {shift:'F', html:'&#102;', hex:0x66 },
			'g': {shift:'G', html:'&#103;', hex:0x67 },
			'h': {shift:'H', html:'&#104;', hex:0x68 },
			'i': {shift:'I', html:'&#105;', hex:0x69 },
			'j': {shift:'J', html:'&#106;', hex:0x6A },
			'k': {shift:'K', html:'&#107;', hex:0x6B },
			'l': {shift:'L', html:'&#108;', hex:0x6C },
			'm': {shift:'M', html:'&#109;', hex:0x6D },
			'n': {shift:'N', html:'&#110;', hex:0x6E },
			'o': {shift:'O', html:'&#111;', hex:0x6F },
			'p': {shift:'P', html:'&#112;', hex:0x70 },
			'q': {shift:'Q', html:'&#113;', hex:0x71 },
			'r': {shift:'R', html:'&#114;', hex:0x72 },
			's': {shift:'S', html:'&#115;', hex:0x73 },
			't': {shift:'T', html:'&#116;', hex:0x74 },
			'u': {shift:'U', html:'&#117;', hex:0x75 },
			'v': {shift:'V', html:'&#118;', hex:0x76 },
			'w': {shift:'W', html:'&#119;', hex:0x77 },
			'x': {shift:'X', html:'&#120;', hex:0x78 },
			'y': {shift:'Y', html:'&#121;', hex:0x79 },
			'z': {shift:'Z', html:'&#122;', hex:0x7A }
		};

		this.upperSet = {
			'Á': {shift:'á', html:'&#_ZZ_;', hex:null, name:'Aacute', info:'capital A, acute accent' },
			'Â': {shift:'â', html:'&#_ZZ_;', hex:null, name:'Acirc', info:'capital A, circumflex accent' },
			'À': {shift:'à', html:'&#_ZZ_;', hex:null, name:'Agrave', info:'capital A, grave accent' },
			'Å': {shift:'å', html:'&#_ZZ_;', hex:null, name:'Aring', info:'capital A, ring' },
			'Ã': {shift:'ã', html:'&#_ZZ_;', hex:null, name:'Atilde', info:'capital A, tilde' },
			'Ä': {shift:'ä', html:'&#_ZZ_;', hex:null, name:'Auml', info:'capital A, dieresis or umlautmark' },
			'Æ': {shift:'æ', html:'&#_ZZ_;', hex:null, name:'AElig', info:'capital AE diphthong(ligature)' },
			'Ç': {shift:'ç', html:'&#_ZZ_;', hex:null, name:'Ccedil', info:'capital C, cedilla' },
			'Ð': {shift:'ð', html:'&#_ZZ_;', hex:null, name:'ETH', info:'capital Eth, Icelandic' },
			'É': {shift:'é', html:'&#_ZZ_;', hex:null, name:'Eacute', info:'capital E, acute accent' },
			'Ê': {shift:'ê', html:'&#_ZZ_;', hex:null, name:'Ecirc', info:'capital E, circumflex accent' },
			'È': {shift:'è', html:'&#_ZZ_;', hex:null, name:'Egrave', info:'capital E, grave accent' },
			'Ë': {shift:'ë', html:'&#_ZZ_;', hex:null, name:'Euml', info:'capital E, dieresis or umlautmark' },
			'Í': {shift:'í', html:'&#_ZZ_;', hex:null, name:'Iacute', info:'capital I, acute accent' },
			'Î': {shift:'î', html:'&#_ZZ_;', hex:null, name:'Icirc', info:'capital I, circumflex accent' },
			'Ì': {shift:'ì', html:'&#_ZZ_;', hex:null, name:'Igrave', info:'capital I, grave accent' },
			'Ï': {shift:'ï', html:'&#_ZZ_;', hex:null, name:'Iuml', info:'capital I, dieresis or umlautmark' },
			'Ñ': {shift:'ñ', html:'&#_ZZ_;', hex:null, name:'Ntilde', info:'capital N, tilde' },
			'Ó': {shift:'ó', html:'&#_ZZ_;', hex:null, name:'Oacute', info:'capital O, acute accent' },
			'Ô': {shift:'ô', html:'&#_ZZ_;', hex:null, name:'Ocirc', info:'capital O, circumflex accent' },
			'Ò': {shift:'ò', html:'&#_ZZ_;', hex:null, name:'Ograve', info:'capital O, grave accent' },
			'Ø': {shift:'ø', html:'&#_ZZ_;', hex:null, name:'Oslash', info:'capital O, slash' },
			'Õ': {shift:'õ', html:'&#_ZZ_;', hex:null, name:'Otilde', info:'capital O, tilde' },
			'Ö': {shift:'ö', html:'&#_ZZ_;', hex:null, name:'Ouml', info:'capital O, dieresis or umlautmark' },
			'Ú': {shift:'ú', html:'&#_ZZ_;', hex:null, name:'Uacute', info:'capital U, acute accent' },
			'Û': {shift:'û', html:'&#_ZZ_;', hex:null, name:'Ucirc', info:'capital U, circumflex accent' },
			'Ù': {shift:'ù', html:'&#_ZZ_;', hex:null, name:'Ugrave', info:'capital U, grave accent' },
			'Ü': {shift:'ü', html:'&#_ZZ_;', hex:null, name:'Uuml', info:'capital U, dieresis or umlautmark' },
			'Ý': {shift:'ý', html:'&#_ZZ_;', hex:null, name:'Yacute', info:'capital Y, acute accent' },
			'A': {shift:'a', html:'&#65;', hex:0x41, name:'Yacute' },
			'B': {shift:'b', html:'&#66;', hex:0x42, name:'Yacute' },
			'C': {shift:'c', html:'&#67;', hex:0x43, name:'Yacute' },
			'D': {shift:'d', html:'&#68;', hex:0x44, name:'Yacute' },
			'E': {shift:'e', html:'&#69;', hex:0x45, name:'Yacute' },
			'F': {shift:'f', html:'&#70;', hex:0x46, name:'Yacute' },
			'G': {shift:'g', html:'&#71;', hex:0x47, name:'Yacute' },
			'H': {shift:'h', html:'&#72;', hex:0x48, name:'Yacute' },
			'I': {shift:'i', html:'&#73;', hex:0x49, name:'Yacute' },
			'J': {shift:'j', html:'&#74;', hex:0x4A, name:'Yacute' },
			'K': {shift:'k', html:'&#75;', hex:0x4B, name:'Yacute' },
			'L': {shift:'l', html:'&#76;', hex:0x4C, name:'Yacute' },
			'M': {shift:'m', html:'&#77;', hex:0x4D, name:'Yacute' },
			'N': {shift:'n', html:'&#78;', hex:0x4E, name:'Yacute' },
			'O': {shift:'o', html:'&#79;', hex:0x4F, name:'Yacute' },
			'P': {shift:'p', html:'&#80;', hex:0x50, name:'Yacute' },
			'Q': {shift:'q', html:'&#81;', hex:0x51, name:'Yacute' },
			'R': {shift:'r', html:'&#82;', hex:0x52, name:'Yacute' },
			'S': {shift:'s', html:'&#83;', hex:0x53, name:'Yacute' },
			'T': {shift:'t', html:'&#84;', hex:0x54, name:'Yacute' },
			'U': {shift:'u', html:'&#85;', hex:0x55, name:'Yacute' },
			'V': {shift:'v', html:'&#86;', hex:0x56, name:'Yacute' },
			'W': {shift:'w', html:'&#87;', hex:0x57, name:'Yacute' },
			'X': {shift:'x', html:'&#88;', hex:0x58, name:'Yacute' },
			'Y': {shift:'t', html:'&#89;', hex:0x59, name:'Yacute' },
			'Z': {shift:'z', html:'&#90;', hex:0x5A, name:'Yacute' }
		}
}


module.exports = LetterSet;
