'use strict';
// https://github.com/unicode-table/unicode-table-data/blob/master/data/alphabets.txt

function LetterSet() {
	if (!(this instanceof LetterSet)) {
		return new LetterSet();
	}
	this.letters = {
		A: {decimal: 65, hex: 0x41, name: 'Uppercase A', html: 'A'},
		a: {decimal: 97, hex: 0x61, name: 'Lowercase a', html: 'a'},
		B: {decimal: 66, hex: 0x42, name: 'Uppercase B', html: 'B'},
		b: {decimal: 98, hex: 0x62, name: 'Lowercase b', html: 'b'},
		C: {decimal: 67, hex: 0x43, name: 'Uppercase C', html: 'C'},
		c: {decimal: 99, hex: 0x63, name: 'Lowercase c', html: 'c'},
		D: {decimal: 68, hex: 0x44, name: 'Uppercase D', html: 'D'},
		d: {decimal: 100, hex: 0x64, name: 'Lowercase d', html: 'd'},
		E: {decimal: 69, hex: 0x45, name: 'Uppercase E', html: 'E'},
		e: {decimal: 101, hex: 0x65, name: 'Lowercase e', html: 'e'},
		F: {decimal: 70, hex: 0x46, name: 'Uppercase F', html: 'F'},
		f: {decimal: 102, hex: 0x66, name: 'Lowercase f', html: 'f'},
		G: {decimal: 71, hex: 0x47, name: 'Uppercase G', html: 'G'},
		g: {decimal: 103, hex: 0x67, name: 'Lowercase g', html: 'g'},
		H: {decimal: 72, hex: 0x48, name: 'Uppercase H', html: 'H'},
		h: {decimal: 104, hex: 0x68, name: 'Lowercase h', html: 'h'},
		I: {decimal: 73, hex: 0x49, name: 'Uppercase I', html: 'I'},
		i: {decimal: 105, hex: 0x69, name: 'Lowercase i', html: 'i'},
		J: {decimal: 74, hex: 0x4A, name: 'Uppercase J', html: 'J'},
		j: {decimal: 106, hex: 0x6A, name: 'Lowercase j', html: 'j'},
		K: {decimal: 75, hex: 0x4B, name: 'Uppercase K', html: 'K'},
		k: {decimal: 107, hex: 0x6B, name: 'Lowercase k', html: 'k'},
		L: {decimal: 76, hex: 0x4C, name: 'Uppercase L', html: 'L'},
		l: {decimal: 108, hex: 0x6C, name: 'Lowercase l', html: 'l'},
		M: {decimal: 77, hex: 0x4D, name: 'Uppercase M', html: 'M'},
		m: {decimal: 109, hex: 0x6D, name: 'Lowercase m', html: 'm'},
		N: {decimal: 78, hex: 0x4E, name: 'Uppercase N', html: 'N'},
		n: {decimal: 110, hex: 0x6E, name: 'Lowercase n', html: 'n'},
		O: {decimal: 79, hex: 0x4F, name: 'Uppercase O', html: 'O'},
		o: {decimal: 111, hex: 0x6F, name: 'Lowercas', html: 'o'},
		P: {decimal: 80, hex: 0x50, name: 'Uppercase P', html: 'P'},
		p: {decimal: 112, hex: 0x70, name: 'Lowercase p', html: 'p'},
		Q: {decimal: 81, hex: 0x51, name: 'Uppercase Q', html: 'Q'},
		q: {decimal: 113, hex: 0x71, name: 'Lowercase q', html: 'q'},
		R: {decimal: 82, hex: 0x52, name: 'Uppercase R', html: 'R'},
		r: {decimal: 114, hex: 0x72, name: 'Lowercase r', html: 'r'},
		S: {decimal: 83, hex: 0x53, name: 'Uppercase S', html: 'S'},
		s: {decimal: 115, hex: 0x73, name: 'Lowercase s', html: 's'},
		T: {decimal: 84, hex: 0x54, name: 'Uppercase T', html: 'T'},
		t: {decimal: 116, hex: 0x74, name: 'Lowercase t', html: 't'},
		U: {decimal: 85, hex: 0x55, name: 'Uppercase U', html: 'U'},
		u: {decimal: 117, hex: 0x75, name: 'Lowercase u', html: 'u'},
		V: {decimal: 86, hex: 0x56, name: 'Uppercase V', html: 'V'},
		v: {decimal: 118, hex: 0x76, name: 'Lowercase v', html: 'v'},
		W: {decimal: 87, hex: 0x57, name: 'Uppercase W', html: 'W'},
		w: {decimal: 119, hex: 0x77, name: 'Lowercase w', html: 'w'},
		X: {decimal: 88, hex: 0x58, name: 'Uppercase X', html: 'X'},
		x: {decimal: 120, hex: 0x78, name: 'Lowercase x', html: 'x'},
		Y: {decimal: 89, hex: 0x59, name: 'Uppercase Y', html: 'Y'},
		y: {decimal: 121, hex: 0x79, name: 'Lowercase y', html: 'y'},
		Z: {decimal: 90, hex: 0x5A, name: 'Uppercase Z', html: 'Z'},
		z: {decimal: 122, hex: 0x7A, name: 'Lowercase z', html: 'z'},
		İ: {decimal: 304, hex: 0x130, name: 'Capital I-dotted', html: '&Idot;'},
		ı: {decimal: 305, hex: 0x131, name: 'Lowercase i-dotless', html: '&imath;'},
		Ö: {decimal: 214, hex: 0xd6, name: 'Latin capital letter O with diaeresis/umlaut', html: '&Ouml;'},
		ö: {decimal: 246, hex: 0xf6, name: 'Latin capital letter O with diaeresis/umlaut', html: '&ouml;'},
		Ü: {decimal: 220, hex: 0xdc, name: 'Latin capital letter U with diaeresis/umlaut', html: '&Uuml;'},
		ü: {decimal: 252, hex: 0xfc, name: 'Lowercase u-umlaut', html: '&uuml;'},
		Ç: {decimal: 199, hex: 0xC7, name: 'Latin capital letter C with cedilla', html: '&Ccedil;'},
		ç: {decimal: 231, hex: 0xE7, name: 'Latin small letter c with cedilla', html: '&ccedil;'},
		Ğ: {decimal: 286, hex: 0x11e, name: 'Capital G-breve', html: '&Gbreve;'},
		ğ: {decimal: 287, hex: 0x11f, name: 'Lowercase g-breve', html: '&gbreve;'},
		Ş: {decimal: 350, hex: 0x15e, name: 'Capital letter S with cedilla', html: '&Scedil;'},
		ş: {decimal: 351, hex: 0x15f, name: 'Lowercase letter s with cedilla', html: '&scedil;'},
		Á: {decimal: 193, hex: 0xc4, name: 'Latin capital letter A with acute', html: '&Aacute;'},
		á: {decimal: 225, hex: 0xe1, name: 'Latin small letter a with acute', html: '&aacute;'},
		É: {decimal: 201, hex: 0xc9, name: 'Latin capital letter E with acute', html: '&Eacute;'},
		é: {decimal: 233, hex: 0xe9, name: 'Latin small letter e with acute', html: '&eacute;'},
		Í: {decimal: 205, hex: 0xcd, name: 'Latin capital letter I with acute', html: '&Iacute;'},
		í: {decimal: 237, hex: 0xed, name: 'Latin small letter i with acute', html: '&iacute;'},
		Ñ: {decimal: 209, hex: 0xd1, name: 'Latin capital letter N with tilde', html: '&Ntilde;'},
		ñ: {decimal: 241, hex: 0xf1, name: 'Latin small letter n with tilde', html: '&ntilde;'},
		Ó: {decimal: 211, hex: 0xd3, name: 'Latin capital letter O with acute', html: '&Oacute;'},
		ó: {decimal: 243, hex: 0xf3, name: 'Latin small letter o with acute', html: '&oacute;'},
		Ú: {decimal: 218, hex: 0xda, name: 'Latin capital letter U with acute', html: '&Uacute;'},
		ú: {decimal: 250, hex: 0xfa, name: 'Latin small letter u with acute', html: '&uacute;'},
		А: {decimal: 1040, hex: 0x410, name: '', html: '&Acy;'},
		а: {decimal: 1072, hex: 0x430, name: '', html: '&acy;'},
		Б: {decimal: 1041, hex: 0x411, name: '', html: '&Bcy;'},
		б: {decimal: 1073, hex: 0x431, name: '', html: '&bcy;'},
		В: {decimal: 1042, hex: 0x412, name: '', html: '&Vcy;'},
		в: {decimal: 1074, hex: 0x432, name: '', html: '&vcy;'},
		Г: {decimal: 1043, hex: 0x413, name: '', html: '&Gcy;'},
		г: {decimal: 1075, hex: 0x433, name: '', html: '&gcy;'},
		Д: {decimal: 1044, hex: 0x414, name: '', html: '&Dcy;'},
		д: {decimal: 1076, hex: 0x434, name: '', html: '&dcy;'},
		Е: {decimal: 1045, hex: 0x415, name: '', html: '&IEcy;'},
		е: {decimal: 1077, hex: 0x435, name: '', html: '&iecy;'},
		Ж: {decimal: 1046, hex: 0x416, name: '', html: '&ZHcy;'},
		ж: {decimal: 1078, hex: 0x436, name: '', html: '&zhcy;'},
		З: {decimal: 1047, hex: 0x417, name: '', html: '&Zcy;'},
		з: {decimal: 1079, hex: 0x437, name: '', html: '&zcy;'},
		И: {decimal: 1048, hex: 0x418, name: '', html: '&Icy;'},
		и: {decimal: 1080, hex: 0x438, name: '', html: '&icy;'},
		Й: {decimal: 1049, hex: 0x419, name: '', html: '&Jcy;'},
		й: {decimal: 1081, hex: 0x439, name: '', html: '&jcy;'},
		К: {decimal: 1050, hex: 0x41a, name: '', html: '&Kcy;'},
		к: {decimal: 1082, hex: 0x43a, name: '', html: '&kcy;'},
		Л: {decimal: 1051, hex: 0x41b, name: '', html: '&Lcy;'},
		л: {decimal: 1083, hex: 0x43b, name: '', html: '&lcy;'},
		М: {decimal: 1052, hex: 0x41c, name: '', html: '&Mcy;'},
		м: {decimal: 1084, hex: 0x43c, name: '', html: '&mcy;'},
		Н: {decimal: 1053, hex: 0x41d, name: '', html: '&Ncy;'},
		н: {decimal: 1085, hex: 0x43d, name: '', html: '&ncy;'},
		О: {decimal: 1054, hex: 0x41e, name: '', html: '&Ocy;'},
		о: {decimal: 1086, hex: 0x43e, name: '', html: '&ocy;'},
		П: {decimal: 1055, hex: 0x41f, name: '', html: '&Pcy;'},
		п: {decimal: 1087, hex: 0x43f, name: '', html: '&pcy;'},
		Р: {decimal: 1056, hex: 0x420, name: '', html: '&Rcy;'},
		р: {decimal: 1088, hex: 0x440, name: '', html: '&rcy;'},
		С: {decimal: 1057, hex: 0x421, name: '', html: '&Scy;'},
		с: {decimal: 1089, hex: 0x441, name: '', html: '&scy;'},
		Т: {decimal: 1058, hex: 0x422, name: '', html: '&Tcy;'},
		т: {decimal: 1090, hex: 0x442, name: '', html: '&tcy;'},
		У: {decimal: 1059, hex: 0x423, name: '', html: '&Ucy;'},
		у: {decimal: 1091, hex: 0x443, name: '', html: '&ucy;'},
		Ф: {decimal: 1060, hex: 0x424, name: '', html: '&Fcy;'},
		ф: {decimal: 1092, hex: 0x444, name: '', html: '&fcy;'},
		Х: {decimal: 1061, hex: 0x425, name: '', html: '&KHcy;'},
		х: {decimal: 1093, hex: 0x445, name: '', html: '&khcy;'},
		Ц: {decimal: 1062, hex: 0x426, name: '', html: '&TScy;'},
		ц: {decimal: 1094, hex: 0x446, name: '', html: '&tscy;'},
		Ч: {decimal: 1063, hex: 0x427, name: '', html: '&CHcy;'},
		ч: {decimal: 1095, hex: 0x447, name: '', html: '&chcy;'},
		Ш: {decimal: 1064, hex: 0x428, name: '', html: '&SHcy;'},
		ш: {decimal: 1096, hex: 0x448, name: '', html: '&shcy;'},
		Щ: {decimal: 1065, hex: 0x429, name: '', html: '&SHCHcy;'},
		щ: {decimal: 1097, hex: 0x449, name: '', html: '&shchcy;'},
		Ъ: {decimal: 1066, hex: 0x42a, name: '', html: '&HARDcy;'},
		ъ: {decimal: 1098, hex: 0x44a, name: '', html: '&hardcy;'},
		Ы: {decimal: 1067, hex: 0x42b, name: '', html: '&Ycy;'},
		ы: {decimal: 1099, hex: 0x44b, name: '', html: '&ycy;'},
		Ь: {decimal: 1068, hex: 0x42c, name: '', html: '&SOFTcy;'},
		ь: {decimal: 1100, hex: 0x44c, name: '', html: '&softcy;'},
		Э: {decimal: 1069, hex: 0x42d, name: '', html: '&Ecy;'},
		э: {decimal: 1101, hex: 0x44d, name: '', html: '&ecy;'},
		Ю: {decimal: 1070, hex: 0x42e, name: '', html: '&YUcy;'},
		ю: {decimal: 1102, hex: 0x44e, name: '', html: '&yucy;'},
		Я: {decimal: 1071, hex: 0x42f, name: '', html: '&YAcy;'},
		я: {decimal: 1103, hex: 0x44f, name: '', html: '&yacy;'},
		Ă: {decimal: 258, hex: 0x102, name: 'Capital A-breve', html: '&Abreve;'},
		ă: {decimal: 259, hex: 0x103, name: 'Lowercase a-breve', html: '&abreve;'},
		Â: {decimal: 194, hex: 0xC2, name: 'Latin capital letter A with circumflex', html: '&Acirc;'},
		â: {decimal: 226, hex: 0xE2, name: 'Latin small letter a with circumflex', html: '&acirc;'},
		Î: {decimal: 206, hex: 0xCE, name: 'Latin capital letter I with circumflex', html: '&Icirc;'},
		î: {decimal: 238, hex: 0xEE, name: 'Latin small letter i with circumflex', html: '&icirc;'},
		Ș: {decimal: 218, hex: 0xDA, name: 'Capital S-comma', html: '&#536;'},
		ș: {decimal: 219, hex: 0xDB, name: 'Lowercase s-comma', html: '&#537;'},
		Ț: {decimal: 538, hex: 0x21a, name: 'Capital T-comma', html: '&#538;'},
		ț: {decimal: 539, hex: 0x21b, name: 'Lowercase t-comma', html: '&#539;'},
		Ţ: {decimal: 354, hex: 0x162, name: 'Capital T-cedille', html: '&Tcedil;'},
		ţ: {decimal: 355, hex: 0x163, name: 'Lowercase t-cedille', html: '&tcedil;'},
		Ą: {decimal: 260, hex: 0x104, name: 'Capital A-cedille', html: '&Aogon;'},
		ą: {decimal: 261, hex: 0x105, name: 'Lowercase a-cedille', html: '&aogon;'},
		Ę: {decimal: 280, hex: 0x118, name: 'Capital E-cedille', html: '&Eogon;'},
		ę: {decimal: 281, hex: 0x119, name: 'Lowercase e-cedille', html: '&eogon;'},
		Ć: {decimal: 262, hex: 0x106, name: 'Capital C-acute', html: '&Cacute;'},
		ć: {decimal: 263, hex: 0x107, name: 'Lowercase c-acute', html: '&cacute;'},
		Ł: {decimal: 321, hex: 0x141, name: 'Capital L-bar', html: '&Lstrok;'},
		ł: {decimal: 322, hex: 0x142, name: 'Lowercase l-bar', html: '&lstrok;'},
		Ń: {decimal: 323, hex: 0x143, name: 'Capital N-acute', html: '&Nacute;'},
		ń: {decimal: 324, hex: 0x144, name: 'Lowercase n-acute', html: '&nacute;'},
		Ś: {decimal: 346, hex: 0x15a, name: 'Capital S-acute', html: '&Sacute;'},
		ś: {decimal: 347, hex: 0x15b, name: 'Lowercase s-acute', html: '&sacute;'},
		Ź: {decimal: 377, hex: 0x179, name: 'Capital Z-acute', html: '&Zacute;'},
		ź: {decimal: 378, hex: 0x17a, name: 'Lowercase z-acute', html: '&zacute;'},
		Ż: {decimal: 379, hex: 0x17b, name: 'Capital Z-dot', html: '&Zdot;'},
		ż: {decimal: 380, hex: 0x17c, name: 'Lowercase z-dot', html: '&zdot;'},
		À: {decimal: 192, hex: 0xC0, name: 'Latin capital letter A with grave', html: '&Agrave;'},
		à: {decimal: 224, hex: 0xE0, name: 'Latin small letter a with grave', html: '&agrave;'},
		Ã: {decimal: 195, hex: 0xC3, name: 'Latin capital letter A with tilde', html: '&Atilde;'},
		ã: {decimal: 227, hex: 0xE3, name: 'Latin small letter a with tilde', html: '&atilde;'},
		Ä: {decimal: 196, hex: 0xC4, name: 'Latin capital letter A with diaeresis', html: '&Auml;'},
		ä: {decimal: 228, hex: 0xE4, name: 'Latin small letter a with diaeresie', html: '&auml;'},
		Å: {decimal: 197, hex: 0xC5, name: 'Latin capital letter A with ring above', html: '&angst;'},
		å: {decimal: 229, hex: 0xE5, name: 'Latin small letter a with ring above', html: '&aring;'},
		Æ: {decimal: 198, hex: 0xc6, name: 'Capital AE Ligature', html: '&AElig;'},
		æ: {decimal: 230, hex: 0xe6, name: 'Lowercase AE Ligature', html: '&aelig;'},
		È: {decimal: 200, hex: 0xC8, name: 'Latin capital letter E with grave', html: '&Egrave;'},
		è: {decimal: 232, hex: 0xE8, name: 'Latin small letter e with grave', html: '&egrave;'},
		Ê: {decimal: 202, hex: 0xCA, name: 'Latin capital letter E with circumflex', html: '&Ecirc;'},
		ê: {decimal: 234, hex: 0xEA, name: 'Latin small letter e with circumflex', html: '&ecirc;'},
		Ë: {decimal: 203, hex: 0xCB, name: 'Latin capital letter E with diaeresis/umlaut', html: '&Euml;'},
		ë: {decimal: 235, hex: 0xEB, name: 'Latin small letter e with diaeresis/umlaut', html: '&euml;'},
		ƒ: {decimal: 131, hex: 0x83, name: 'Latin small letter f with hook', html: '&fnof;'},
		Ì: {decimal: 204, hex: 0xCC, name: 'Latin capital letter I with grave', html: '&Igrave;'},
		ì: {decimal: 236, hex: 0xEC, name: 'Latin small letter i with grave', html: '&igrave;'},
		Ï: {decimal: 207, hex: 0xCF, name: 'Latin capital letter I with diaeresis/umlaut', html: '&Iuml;'},
		ï: {decimal: 239, hex: 0xEF, name: 'Latin small letter i with diaeresis/umlaut', html: '&iuml;'},
		Ò: {decimal: 210, hex: 0xD2, name: 'Latin capital letter O with grave', html: '&Ograve;'},
		ò: {decimal: 242, hex: 0xF2, name: 'Latin small letter o with grave', html: '&ograve;'},
		Ô: {decimal: 212, hex: 0xD4, name: 'Latin capital letter O with circumflex', html: '&Ocirc;'},
		ô: {decimal: 244, hex: 0xF4, name: 'Latin small letter o with circumflex', html: '&ocirc;'},
		Õ: {decimal: 213, hex: 0xD5, name: 'Latin capital letter O with tilde', html: '&Otilde;'},
		õ: {decimal: 245, hex: 0xF5, name: 'Latin small letter o with tilde', html: '&otilde;'},
		Ø: {decimal: 216, hex: 0xD8, name: 'Latin capital letter O with slash', html: '&Oslash;'},
		ø: {decimal: 248, hex: 0xF8, name: 'Latin small letter o with slash', html: '&oslash;'},
		Š: {decimal: 138, hex: 0x8A, name: 'Latin capital letter S with caron', html: '&Scaron;'},
		š: {decimal: 154, hex: 0x9A, name: 'Latin small letter S with caron', html: '&scaron;'},
		ß: {decimal: 223, hex: 0xDF, name: 'Latin small letter sharp s - ess-zed; SZ ligature', html: '&szlig;'},
		Ù: {decimal: 217, hex: 0xD9, name: 'Latin capital letter U with grave', html: '&Ugrave;'},
		ù: {decimal: 249, hex: 0xF9, name: 'Latin small letter u with grave', html: '&ugrave;'},
		Û: {decimal: 219, hex: 0xDB, name: 'Latin capital letter U with circumflex', html: '&Ucirc;'},
		û: {decimal: 251, hex: 0xFB, name: 'Latin small letter u with circumflex', html: '&ucirc;'},
		Ÿ: {decimal: 159, hex: 0x9F, name: 'Latin capital letter Y with diaeresis', html: '&Yuml;'},
		ÿ: {decimal: 255, hex: 0xFF, name: 'Latin small letter y with diaeresis', html: '&yuml;'},
		Ý: {decimal: 221, hex: 0xDD, name: 'Latin capital letter Y with acute', html: '&Yacute;'},
		ý: {decimal: 253, hex: 0xFD, name: 'Latin small letter y with acute', html: '&yacute;'},
		Ž: {decimal: 142, hex: 0x8E, name: 'Latin captial letter Z with caron', html: '&Zcaron;'},
		ž: {decimal: 158, hex: 0x9E, name: 'Latin small letter z with caron', html: '&zcaron;'},
		Œ: {decimal: 338, hex: 0x8C, name: 'Latin capital ligature O', html: '&OElig;'},
		œ: {decimal: 339, hex: 0x9C, name: 'Latin small ligature o', html: '&oelig;'},
		Ð: {decimal: 208, hex: 0xD0, name: 'Latin capital letter ET', html: '&ETH;'},
		Þ: {decimal: 222, hex: 0xDE, name: 'Latin capital letter THOR', html: '&THORN;'},
		ð: {decimal: 240, hex: 0xF0, name: 'Latin small letter et', html: '&eth;'},
		þ: {decimal: 254, hex: 0xFE, name: 'Latin small letter thor', html: '&thorn;'},
		Ē: {decimal: 274, hex: 0x112, name: 'Capital E-umlaut', html: '&Emacr;'},
		ē: {decimal: 275, hex: 0x113, name: 'Lowercase e-umlaut', html: '&emacr;'},
		Ī: {decimal: 298, hex: 0x12a, name: 'Capital I-umlaut', html: '&Imacr;'},
		ī: {decimal: 299, hex: 0x12b, name: 'Lowercase i-umlaut', html: '&imacr;'},
		Ō: {decimal: 332, hex: 0x14c, name: 'Capital O-umlaut', html: '&Omacr;'},
		ō: {decimal: 333, hex: 0x14d, name: 'Lowercase o-umlaut', html: '&omacr;'},
		Ū: {decimal: 362, hex: 0x16a, name: 'Capital U-umlaut', html: '&Umacr;'},
		ū: {decimal: 363, hex: 0x16b, name: 'Lowercase u-umlaut', html: '&umacr;'},
		Α: {decimal: 913, hex: 0x391, name: 'Capital Alpha', html: '&Alpha;'},
		α: {decimal: 945, hex: 0x3b1, name: 'Lowercase Alpha', html: '&alpha;'},
		Β: {decimal: 914, hex: 0x392, name: 'Capital Beta', html: '&Beta;'},
		β: {decimal: 946, hex: 0x3b2, name: 'Lowercase Beta', html: '&beta;'},
		Γ: {decimal: 915, hex: 0x393, name: 'Capital Gamma', html: '&Gamma;'},
		γ: {decimal: 947, hex: 0x3b3, name: 'Lowercase Gamma', html: '&gamma;'},
		Δ: {decimal: 916, hex: 0x394, name: 'Capital Delta', html: '&Delta;'},
		δ: {decimal: 948, hex: 0x3b4, name: 'Lowercase Delta', html: '&delta;'},
		Ε: {decimal: 917, hex: 0x395, name: 'Capital Epsilon', html: '&Epsilon;'},
		ε: {decimal: 949, hex: 0x3b5, name: 'Lowercase Epsilon', html: '&epsi;'},
		Ζ: {decimal: 918, hex: 0x396, name: 'Capital Zeta', html: '&Zeta;'},
		ζ: {decimal: 950, hex: 0x3b6, name: 'Lowercase Zeta', html: '&zeta;'},
		Η: {decimal: 919, hex: 0x397, name: 'Capital Eta', html: '&Eta;'},
		η: {decimal: 951, hex: 0x3b7, name: 'Lowercase Eta', html: '&eta;'},
		Θ: {decimal: 920, hex: 0x398, name: 'Capital Theta', html: '&Theta;'},
		θ: {decimal: 952, hex: 0x3b8, name: 'Lowercase Theta', html: '&theta;'},
		Ι: {decimal: 921, hex: 0x399, name: 'Capital Iota', html: '&Iota;'},
		ι: {decimal: 953, hex: 0x3b9, name: 'Lowercase Iota', html: '&iota;'},
		Κ: {decimal: 922, hex: 0x39a, name: 'Capital Kappa', html: '&Kappa;'},
		κ: {decimal: 954, hex: 0x3ba, name: 'Lowercase Kappa', html: '&kappa;'},
		Λ: {decimal: 923, hex: 0x39b, name: 'Capital Lambda', html: '&Lambda;'},
		λ: {decimal: 955, hex: 0x3bb, name: 'Lowercase Lambda', html: '&lambda;'},
		Μ: {decimal: 924, hex: 0x39c, name: 'Capital M', html: '&Mu;'},
		μ: {decimal: 956, hex: 0x3bc, name: 'Lowercase M', html: '&mu;'},
		Ν: {decimal: 925, hex: 0x39d, name: 'Capital N', html: '&Nu;'},
		ν: {decimal: 957, hex: 0x3bd, name: 'Lowercase N', html: '&nu;'},
		Ξ: {decimal: 926, hex: 0x39e, name: 'Capital X', html: '&Xi;'},
		ξ: {decimal: 958, hex: 0x3be, name: 'Lowercase X', html: '&xi;'},
		Ο: {decimal: 927, hex: 0x39f, name: 'Capital Omicron', html: '&Omicron;'},
		ο: {decimal: 959, hex: 0x3bf, name: 'Lowercase Omicron', html: '&omicron;'},
		Π: {decimal: 928, hex: 0x3a0, name: 'Capital Pi', html: '&Pi;'},
		π: {decimal: 960, hex: 0x3c0, name: 'Lowercase Pi', html: '&pi;'},
		Ρ: {decimal: 929, hex: 0x3a1, name: 'Capital Rho', html: '&Rho;'},
		ρ: {decimal: 961, hex: 0x3c1, name: 'Lowercase Rho', html: '&rho;'},
		Σ: {decimal: 931, hex: 0x3a3, name: 'Capital Sigma', html: '&Sigma;'},
		σ: {decimal: 963, hex: 0x3c3, name: 'Lowercase Sigma', html: '&sigma;'},
		ς: {decimal: 962, hex: 0x3c2, name: 'Lowercase Final Sigma', html: '&sigmaf;'},
		Τ: {decimal: 932, hex: 0x3a4, name: 'Capital Tau', html: '&Tau;'},
		τ: {decimal: 964, hex: 0x3c4, name: 'Lowercase Tau', html: '&tau;'},
		Υ: {decimal: 933, hex: 0x3a5, name: 'Capital Upsilon', html: '&Upsilon;'},
		υ: {decimal: 965, hex: 0x3c5, name: 'Lowercase Upsilon', html: '&upsi;'},
		Φ: {decimal: 934, hex: 0x3a6, name: 'Capital Phi', html: '&Phi;'},
		φ: {decimal: 966, hex: 0x3c6, name: 'Lowercase Phi', html: '&phi;'},
		Χ: {decimal: 935, hex: 0x3a7, name: 'Capital Chi', html: '&Chi;'},
		χ: {decimal: 967, hex: 0x3c7, name: 'Lowercase Chi', html: '&chi;'},
		Ψ: {decimal: 936, hex: 0x3a8, name: 'Capital Psi', html: '&Psi;'},
		ψ: {decimal: 968, hex: 0x3c8, name: 'Lowercase Psi', html: '&psi;'},
		Ω: {decimal: 937, hex: 0x3a9, name: 'Capital Omega', html: '&ohm;'},
		ω: {decimal: 969, hex: 0x3c9, name: 'Lowercase Omega', html: '&omega;'},
		Ě: {decimal: 282, hex: 0x11a, name: 'Capital E-hache', html: '&Ecaron;'},
		ě: {decimal: 283, hex: 0x11b, name: 'Lowercase e-hache', html: '&ecaron;'},
		Ů: {decimal: 366, hex: 0x16e, name: 'Capital U-ring', html: '&Uring;'},
		ů: {decimal: 367, hex: 0x16f, name: 'Lowercase u-ring', html: '&uring;'},
		Č: {decimal: 268, hex: 0x10c, name: 'Capital C-hache/caron', html: '&Ccaron;'},
		č: {decimal: 269, hex: 0x10d, name: 'Lowercase c-hache/caron', html: '&ccaron;'},
		ď: {decimal: 271, hex: 0x10f, name: 'd-apostrophe', html: '&dcaron;'},
		ť: {decimal: 357, hex: 0x165, name: 't-apostrophe', html: '&tcaron;'},
		Ĺ: {decimal: 313, hex: 0x139, name: 'Capital L-acute', html: '&Lacute;'},
		ĺ: {decimal: 314, hex: 0x13a, name: 'Lowercase l-acute', html: '&lacute;'},
		Ň: {decimal: 327, hex: 0x147, name: 'Capital N-hache/caron', html: '&Ncaron;'},
		ň: {decimal: 328, hex: 0x148, name: 'Lowercase n-hache/caron', html: '&ncaron;'},
		Ŕ: {decimal: 340, hex: 0x154, name: 'Capital R-acute', html: '&Racute;'},
		ŕ: {decimal: 341, hex: 0x155, name: 'Lowercase r-acute', html: '&racute;'},
		Ř: {decimal: 344, hex: 0x158, name: 'Capital R-hache/caron', html: '&Rcaron;'},
		ř: {decimal: 345, hex: 0x159, name: 'Lowercase r-hache/caron', html: '&rcaron;'}
	};
}

LetterSet.prototype.isLetter = function (char) {
	return this.letters.hasOwnProperty(char);
};

LetterSet.prototype.allCharacters = function () {
	return Object.keys(this.letters);
};

LetterSet.prototype.hex = function (char) {
	return this.letters[char].hex;
};

LetterSet.prototype.decimal = function (char) {
	return this.letters[char].decimal;
};

LetterSet.prototype.name = function (char) {
	return this.letters[char].name;
};

module.exports = LetterSet;
